### ISSUE TITLE
Unwanted log messages for each REST API request

### ISSUE THREAD

**Issue by thd6n75** [AppDaemon/appdaemon#1035]
I have an app that registers an endpoint via `register_endpoint()` ( https://appdaemon.readthedocs.io/en/latest/AD_API_REFERENCE.html#api ).  I have 4 REST sensors configured in homeassistant ( https://www.home-assistant.io/integrations/rest/ ) to hit this API to retrieve state information that the API provides.

I'm looking for a way to eliminate these log messages.  They occur every single minute:

```
INFO AppDaemon: Previous message repeated 4 times
INFO AppDaemon: API Call to my_app_name: status: 200 OK
```

These log messages aren't produced by my app, they are produced by appdaemon itself.

**Comment by ReneTode** [comment]
the only way i know to get away from those messages is not to use the API when its not needed.
and for communication with HA REST is absolutely not needed.

**Comment by thd6n75** [comment]
This app provides an API for HA to query for sensor status.  These are sensors that appdaemon "manufactures" - it is the source of truth for those entities.  So it's always needed, and HA performs those health checks once per minute.  I can't just not use it.

For context, in case it helps: I have a whole-house energy meter.  The appdaemon app watches for changes in power consumption, and makes inferences about what devices just turned on/off.  For example, I can detect when someone turns on a vacuum cleaner, or when the electric stove turns on.  Appdaemon maintains entity state in memory, and HA queries appdaemon to get the state (on/off, current estimated power consumption) of the vacuum cleaner/stove/etc.

**Comment by ReneTode** [comment]
yes you can not use it.

you can create HA sensors with set_state() or with mqtt
the advantage is that you get the state in HA immediatly and HA doesnt need to poll anything.

i think the best way for you would be:
```
self.set_state("binary_sensor.vacuum", state = "on")
```
AD and HA have a fulltime communication (websocket)
there is no need to create any kind of other communication between HA and AD, because everything can be done in a way that uses the websocket connection.

**Comment by thd6n75** [comment]
Ok, I probably could refactor, but it would add a non-trivial amount of complexity.  I don't want to get into a lot of detail but it would likely involve adding counters, timers, and possibly threads.

Alternately, maybe we could just enable folks to control the logging?

**Comment by ReneTode** [comment]
i personally think you created complexity and you would get rid of it by refactoring.

and the changes wouldnt be that big.

instead of using REST sensors in HA to poll AD, you can use a simple run_every every 60 seconds
and push the data with set_state.

im not an AD dev anymore, but i know that changes are not going to go fast at the moment because the devs have RL stuff going on.
controlling all logging would be a big change, and controlling 1 or more single log types would be a step that would only lead to more questions asking for control.
so personally i dont expect such a change will come in a short time.

but im happy to help you rethink how your apps are working.
come to discord and we can talk about it, because i think you can avoid the complexity you know have.

**Comment by thd6n75** [comment]
I refactored this, `run_every` was key, thanks
