### ISSUE TITLE
Offer alternative Docker image not based on Alpine (for example Ubuntu)

### ISSUE THREAD

**Issue by Hubro** [AppDaemon/appdaemon#1073]
Using Alpine for Python based applications can be a real pain.

https://pythonspeed.com/articles/alpine-docker-python/

For example, if I use the unmodified AppDaemon image and I add these Python dependencies to `requirements.txt`:

```
numpy==1.19.4
scipy==1.5.4
```

This is *slooooow* since we can't get pre-compiled libraries on Alpine (due to musl libc) and additionally it ultimately fails due to missing dependencies.

In other words, there is no way for me to install these libraries without modifying the Docker image :sigh:

If the image was based on Ubuntu instead, both these packages would install in seconds since they have pre-compiled versions.

**Comment by ReneTode** [comment]
when people are getting to a point where this is a problem i just advise: dont use docker.
use python venv and you will have ubuntu when your system is ubuntu.

**Comment by Hubro** [comment]
Not an option for me, everything on my HA server is deployed using Docker. Changing that would be far more hassle than using a different Docker image. (Deployment scripts, backup strategy etc.)

**Comment by ReneTode** [comment]
if you are that much of a docker user, then create your own docker.
and i believe you just stick to docker because your familiar with it. your system probably already got python and venv installed.
so its probably just as easy to use venv, but it would mean freedom from created dockers, and not a shitload of installed OSes

i dont think the devs are willing to start creating several different images (i could be wrong though)
that would mean more work with every release, just for others, because they dont use it themselves.

**Comment by Hubro** [comment]
@ReneTode It's extremely common for Docker images to provide an Alpine and a non-Alpine flavor (for example, the Python image that AppDaemon's image is based on does this), so I figure it's worth asking.

Also unless I'm overlooking something, it would be extremely easy to port the AppDaemon Dockerfile. It contains a grand total of 11 lines (ignoring comments), and only 4 of them are specific to Alpine. You could just copy paste the current Dockerfile and replace `FROM python:3.8-alpine` with `FROM python:3.8`, then change the `apk` lines to equivalent `apt-get` lines.

It would make life easier for any user that installs a lot of Python libraries, especially heavy compiled libraries like numpy and scipy. But if the authors decide it's not worth it that's completely fine.

**Comment by ReneTode** [comment]
i know alpine isnt the best choice. because a lot of hassio users complain about just what you tell.
but creating it is up to the dev that isnt even using it. (andrew is working with venv, which is the most logical choice, and advised choice for AD in most cases)

i am not a docker user myself, and if i would be offering something like AD, then i would just say: if you want a docker, create it yourself, the files are there. Andrew already does more and provides a docker image.

and maybe he will also think about providing another image. but i would get your hopes up that that will be soon.
if you know how to, and think it could also help other users, then please create such an image and provide it for others.

**Comment by DTTerastar** [comment]
I think it's wierd to be so docker phobic, but attempting to use the most advanced docker image (alpine).  Just only use a debian based image and be done with it.

**Comment by DTTerastar** [comment]
@Hubro https://hub.docker.com/r/dtterastar/appdaemon is up with this fix and it fixes the python trying to build binaries from source.

**Comment by ReneTode** [comment]
> I think it's wierd to be so docker phobic

im not docker phobic. i just dont use it because in my opinion its not the best tool to install AD ;) 

but thx for providing others an alternative.

**Comment by mion00** [comment]
In the last weeks there has been some major updates in the `dev` branch to the way we build the Docker image.
If one requires these kind of scientific packages, it should be possible to install pre-compiled wheels from the Alpine repository [e.g: scipy](https://pkgs.alpinelinux.org/packages?name=py3-scipy&branch=v3.17&repo=&arch=&maintainer=), using the `system_packages.txt` files.

As this issue demonstrates, there was some interest in using a `Debian`-based Docker image, with some volunteers stepping in with their solutions.
Thanks to the new CI pipeline building multiple Docker images should be technically feasible, but this is a decision that should be taken by the maintainer: do we, as AppDaemon project, want to officially support two set of Docker images for our user base? 
This would bring one hand major flexibility on the end-user side, but on the other would increase the effort on our side to maintain two different images, each having their subtle differences.

**Comment by acockburn** [comment]
I am ok with alternatives, but I am not OK with maintaining things I don't regularly use and don't have a good understanding of. If someone wants a different kind of docker image, I am open to that, but I want that person to own and maintain it on behalf of AppDaemon, starting from an initial PR.
