### ISSUE TITLE
Application level constraints don't work when using adbase the "new way"

### ISSUE THREAD

**Issue by Justihar** [AppDaemon/appdaemon#1105]
Have not tried all of the constraint types but can confirm that constrain_input_boolean doesn't work when utilizing the "new" method of creating AD apps by inheriting the adapi.ADBase class. The constraints do appear to be part of the hassapi so I imagine this is why they are not working. Additionally custom constraints are not part of the adapi.

**Comment by ReneTode** [comment]
do the constrains also not work on callback level, when you use plugin api?
hass = self.get_plugin_api("hass")
hass.listen_state(self.cb, entity, constrain_iput_boolean = "...")

because most constraints are hass related anyway.
that they dont work on app level is also logical, because the app is not aware on which plugin it needs to depend.

at this moment all contraints (except custom) should 100% depend on hass api.

**Comment by Justihar** [comment]
Rene, that is a good idea, didn't think to try it at callback level so I tried it with a basic app and it doesn't work. I can see it passing the arguments through to the callback but it runs regardless of the state of the constraint.

**Comment by ReneTode** [comment]
app level plugin constraint can also in the future only work when the app depends on a plugin.

there was a new constraint system planned that makes it possible to use constraints also independant from a plugin.
but as you know is most development on hold.

i know that odia spoke about moving some constraints (like person) from the plugin to ad api, but i think that was never realised.

register constraint should also at least be available in the plugin api or in ad api (i dont know which), because its there when you inherit from a plugin.
but that also is just available on callback level in "new style" apps.

**Comment by Odianosen25** [comment]
@Justihar ,

`register_constraint` is an `adbase` level api, so actually using the new style, you can simply `self.register_constraint`, without the `adapi` side of things and you should be good.

So in that case, just make use of the regular constraint to create a custom constraint as Rene has advised and you should all be good.

I will be closing this now, and if you not satisfied, do re-open.

Regards
