### ISSUE TITLE
Error setting temperature of climate entity in HA

### ISSUE THREAD

**Issue by nielsfaber** [AppDaemon/appdaemon#1106]
When I execute this:
```
        self.call_service(
            "climate/set_temperature",
            entity_id=self.config["thermostat_entity"],
            temperature=new_setpoint,
        )
        self.log("updating setpoint for {} to {}".format(self.config["thermostat_entity"], new_setpoint))
```

It logs the following:
```
2021-01-02 12:10:55.289486 INFO zone_control: updating setpoint for climate.studyroom to 21.5,
2021-01-02 12:10:55.286374 WARNING AppDaemon: Unknown service (default/climate/set_temperature) in call_service from zone_control
```

Perhaps I'm doing something wrong, I couldn't find any example on how to set the temperature setpoint for a HA entity.

**Comment by ReneTode** [comment]
youll need to lookup the correct service on HA and confirm that its an existing service with the correct settings.

if it is an existing service with the correct settings, then its possible that the climate intergration from HA was slower then the HA started event on HA. in that case it will work after restarting AD.

**Comment by nielsfaber** [comment]
@ReneTode  thanks for the quick reply! 

Regarding:
> youll need to lookup the correct service on HA and confirm that its an existing service with the correct settings.

I did a sanity check in HA, the service executes fine from the developer tools:
![image](https://user-images.githubusercontent.com/16861605/103457087-68e15700-4cfc-11eb-81d3-b66e19adef39.png)

Regarding:
>  its possible that the climate intergration from HA was slower then the HA started event on HA. in that case it will work after restarting AD.

This is a bit magic to me. It's not like I execute the AD script right after restarting HA (actually my HA instance has an uptime of over a week), so this event is far in the past.

But I did as you said and restarted AD.
This seemed to do the job fine!
I am not sure how/why this works, as I thought that AD does not require restarts (it auto-reloads scripts upon file changes).
But from now on I know what to do if something like this happens.

Thanks a lot!

**Comment by ReneTode** [comment]
> This is a bit magic to me. It's not like I execute the AD script right after restarting HA (actually my HA instance has an uptime of over a week), so this event is far in the past.

let me explain it a bit more.
HA has changed a lot in the last year.
1 thing they changed is that HA says its ready and its frontend is available, BEFORE all intergrations are up and running.
AD at that point connects to HA and picks up all available services.
but the service belongs to the climate intergrations, which isnt there at that moment, so AD doesnt know that service exists.
AD doesnt know how to find new services in HA after the moment that AD has connected to HA.
the result is that the service stays unknown untill AD reconnects to HA. (restart from AD)

the only way to make sure that AD knows all services at the moment is:
1) put a delay in the AD configuration, so that intergrations are ready before AD starts (when you restart your device or HA and AD at once)
2) restart AD a longer time after you have restarted HA.

but im glad it works now.

**Comment by nielsfaber** [comment]
Thanks a lot for clearing that up!
Actually I experienced similar problems with a custom_component I maintain.
HA lately tends to make architectural changes without overseeing the side-effects. Can cause quite some nailbiting.
There should really be an event (or maybe it already exists?) that fires when an integration is loaded, such that AD could subscribe to it and re-fetch the services list.
IMO the fact that AD can gracefully handle disconnects and reconnects of HA is one of its strong points.
I have no idea about the architecture of AD, but perhaps there are ways to keep it in sync with HA (worst-case by polling).
Anyway, I’m using AD for about a year now and I have seen it only in the last week. So this is a very minor problem.
Thanks again for helping me out!

**Comment by ReneTode** [comment]
there might be such events noawadays.
but HA evolves almost on daily basis, with no regards to anyone.
and the devs from AD have been kept busy IRL for a long time now (and noone can really tell if and how soon that changes)
to keep up with HA is for a program like AD almost a dayjob.

so as helper i constantly point the best way out to users.

the problem is known, at least. and for now the best solution is a delay or a restart.
