### ISSUE TITLE
External commands / HADASHBOARD not listening for events?

### ISSUE THREAD

**Issue by clyra** [AppDaemon/appdaemon#1146]
Hi,

The docs said that you can navigate to another page using events (https://appdaemon.readthedocs.io/en/latest/DASHBOARD_CREATION.html?highlight=external%20command#external-commands). But going to the homeassistant developer tools->events and firing a hadashboard event doesnt seem to work. I tried with the following:

 ```
   Event type
        hadasboard

    Event Data (Yaml, optional)
      command: navigate
      timeout: 10
      target: Cozinha8-main
      sticky: 0
```

I couldnt find anything about this event on the appdaemon logs.  There's also this post on HA forum describing a similar problem:  https://community.home-assistant.io/t/changing-dashboards-with-scripts-forcing-apdeamon-to-change-skins-remotly/262946

Also, as I understood from the docs this should change the page on all devices dashboards, right? is there a way to limit which device should receive the "navigate" command?  perhaps using namespaces?

**Comment by ReneTode** [comment]
because of changes in HA i have seen several people telling that it doesnt work anymore when you fire the event in HA.
the workaround for that is a simple app in AD that listens to a boolean, automation or script in HA.

an example is somewhere on the HA forum.

there is no way to change 1 single dashboard on 1 device. that is simply not possible because of the way http works.
the only workaround for that that i have found is by using fully kiosk.

**Comment by clyra** [comment]
I did a little digging into this and couldn't find a reference to something like ["event_type"] == "hadasboard" in the code, but I did find that the dash_navigate function fires a event named "__HADASHBOARD_EVENT" into ad event bus. Changing the event type in HA developers tools/events to "__HADASHBOARD_EVENT" doest the trick and the dashboard changes as expected. Also on appdaemon/assets/javascript/dashboard.js there is a line that reads "self.stream.listen_event('*', '__HADASHBOARD_EVENT', self.update_dash); ".   So i guess that somewhere along the development this has changed and it didnt got to the docs.

**Comment by acockburn** [comment]
Thanks for figuring that out - we'll leave this open to remind us to fix the docs.
________________________________

**Comment by ReneTode** [comment]
thx.
yes you are right, the eventname has changed, and at that moment probably the fact that its available for users was forgotten.

thx. for looking into it.

**Comment by clyra** [comment]
Btw... I think that per device navigate is not too difficult to achieve, but I dont know enough JS to do that.  There's a custom component called browser_mod that creates a "device id" for each browser/machine. It uses code from thomasloven/lovelace-card-tools (https://github.com/thomasloven/lovelace-card-tools/blob/master/src/deviceID.js). I think that if dashboard.js call this to set a deviceID, this information could be later used in event_data of the __HADASHBOARD_EVENT to choose if the device should navigate to another dashboard or not.

**Comment by ReneTode** [comment]
> Btw... I think that per device navigate is not too difficult to achieve

i have given it my thoughts over it a lot of times over the years, but it is difficult.
yeah indeed dashboard could set a device id for each device.
but you cant provide that id in the dashboard configuration.

so AD would set a unique ID, but you wont know what ID belongs to what device.
and if you dont know the ID you can send anything to it.

if there was an extra option added to dashboard to set an ID, then that dashboard couldnt be used on 2 devices anymore.

so allthough i would really like an option for it in AD, i dont see a usefull way to do so.

the only option would be an optional device ID in the dash file, and if that is used it cant be used on more then 1 device at a time

**Comment by clyra** [comment]
Hi,

It could be done the same way browser_mod do. You could log it and see at the appdaemon admin/log page, create a special widget that shows it, etc... I also like the ideia of ID on the dashboard, but for the users that use the same dashboard on various devices, it will not work. Anyway, we can do both :-).

**Comment by acockburn** [comment]
Allow each dash to listen for zero or more specific IDs, don’t assign an ID to a dashboard. Then you can define your own IDs and use each one for one or more dashes. The event specifies the ID you want to send. One ID could target an individual dash, another could target 2 or 3 that you specify, no ID could target all.

**Comment by ReneTode** [comment]
> It could be done the same way browser_mod do. You could log it and see at the appdaemon admin/log page, create a special widget that shows it, etc... 

that could be done, but then you cant use it in automations, because it wouldnt be the same every time.

> Allow each dash to listen for zero or more specific IDs, don’t assign an ID to a dashboard. Then you can define your own IDs and use each one for one or more dashes. The event specifies the ID you want to send. One ID could target an individual dash, another could target 2 or 3 that you specify, no ID could target all.

that could indeed work.
but then the most logical implementation way i see is:
in the dash file add an (optional) option like:
```
dashboard_ids:
  - livingroom
  - livingarea
```
in automations you then can send information (or reload, or change dashboard) to all dashboards that have the ID livingroom or livingarea set.

that would be a good solution. (and even easier then the fully kiosk solution i use now.)

allthough ...
you still dont send it to a specific device, so you would need to add the ids to all dashboards that are used on that specific device. and if you use dashboards on a lot of devices that could get very ugly.

another option would be adding a setting to dashboard that shows up the first time the device loads a dashboard asking for an ID. and then save it on that device in a cookie and reuse that everytime. 
then you are really device specific.

**Comment by clyra** [comment]
`that could be done, but then you cant use it in automations, because it wouldnt be the same every time.`

No, it is the same. That code uses a javascript function called "localStorage" which is a kind of persistent cookie. So, unless the user chooses to clean cookies, change browser or is using a anonymous tab, the deviceID will not change.

**Comment by ReneTode** [comment]
> No, it is the same. That code uses a javascript function called "localStorage" which is a kind of persistent cookie. So, unless the user chooses to clean cookies, change browser or is using a anonymous tab, the deviceID will not change.

its still not a good solution. because every time the cookie changes, automations also fail.
in that case its better to use a selfset ID instead of an automated ID, because then the user can keep the ID always the same, and doesnt need to change automations ever.
and with a self set ID the options like Andrew suggested (2 or more devices doing the same) would also be possible.

**Comment by clyra** [comment]
it's not there yet, but the first part using localstorage is done and on a PR. There's also a custom_widget to show the device id.

**Comment by ReneTode** [comment]
automated ID is just the wrong way. even if you create the option to see it.

with an automated ID every time the cookie is deleted you need to change your automations.
the deviceID should be manually set on the device, not automaticly set.

a better way is to have a widget that SETS the ID, rather then that it shows the autogenerated ID.

**Comment by clyra** [comment]
Hi,

The automated id is save on a "persistent" cookie, not a session one. So even if you close/open the browser it will persist. Unless, of course, if the user explicit choose to wipe the cookies. Anyway, setting the id thru a widget is easy, and I'm working on it right now. I'm also doing the other approach which i'm calling "dashid". If defined it will match a substring of dashboard title, i.e., if you set a dashid = floor1, all the dashboards named like "floor1 - lights", or "floor1 - sensors" will navigate. what you think? this way we can address groups of devices.

**Comment by ReneTode** [comment]
> The automated id is save on a "persistent" cookie, not a session one. So even if you close/open the browser it will persist. Unless, of course, if the user explicit choose to wipe the cookies.

which can happen for many reasons. and i rather give in the ID new in the device when that happens, then that i need to change my automations and need to find out in which automations and on what places i used that ID.
it will also make automations better readable, because with a set ID you got a friendly name, with an automated ID not.

>  if you set a dashid = floor1, all the dashboards named like "floor1 - lights", or "floor1 - sensors" will navigate. what you think? this way we can address groups of devices.

when we got a set device ID, then that is obsolete in my eyes.
because then you just give 2 devices the same name and both will be addressed.
using the dashname wont work when you use 1 dashboard on several devices, but only want to change 1 device by automation.

**Comment by clyra** [comment]
PR done. having choices is nice... use what you want :-).
