### ISSUE TITLE
[Feature Request/Proposal] dash_command / External commands

### ISSUE THREAD

**Issue by clyra** [AppDaemon/appdaemon#1164]
Currently a dashboard may use just one external command: "navigate". I'd like to implementing a few other commands and I'm wondering the best way to do that. So the very basic would be something like:

`def dash_command(self, **kwargs)
      self.fire_event("__HADASBOARD_EVENT, **kwargs)` 

At this.update_dash of dashboard.js should be possible to receive and act on this new event/command. For example:

`if (data.data.command === "background")
             {
                document.body.style.background = "url('" + data.data.url + "')";
             } `

so calling dash_command(command=background, url='/custom_css/cubes.jpg') should set the background image of a dashboard (better yet using "deviceid" :-) ).

This raises a few questions:
- Should we have a dash_<command> for each command?
- Should we have a dash_command at all, since we could just use fire_event?
- Should we place the commands on dashboard.js or there's a better place to do that? is there a place to "custom_commands" ?

I also would like to implement a notification command... it should be easy with "alert(msg)", but I'm sure that there is better options.

Another approach should be do all that using custom_widgets. So all the js code could go in custom_widget and it just reacts to a entity state, but in this case, is there a way to have hidden widgets? So you could include it on your dashboard but it doesnt use screen space?

what you think?

**Comment by ReneTode** [comment]
at the moment i havent found a way to listen to events in widgets, i believe dashboard needs some work to get any other event in dashboard.
as soon as a widget can listen to an event there is no need for other functions because you can use fire_event()
in skins you can create the same amount of js, in body and in head, so as soon as all events are available in widgets, they should also be available in other parts from dashboards.

i created a general popup for my dashboards, which also can be used for notifications.
but i must say that i dont use it for that, because i use fully kiosk (which gives a hell of a lot more options to control the device showing a dashboard) and i can create a message with that also if i like.
but for the dashboards where i find messages important i just use a widget that shows the message.

i dont think alert is a good option, because if im not mistaken, it will block the other code.
you cant hide widgets, you can only let it seem as empty space.

in skins you can do everything. change background on a certain time, based on a dashboard name, and way more.

personally i use my skins to have animated backgrounds that are automaticly changed based on the season.
also i have grouped widgets.

if you want to know more about that i ask you to come to our discord server.

**Comment by clyra** [comment]
As we found, this can be done including user custom js scripts. So it may be best to leave this out of hadashboard for now.  I'm closing the issue.
