### ISSUE TITLE
Locking decorator documentation wrong?

### ISSUE THREAD

**Issue by sithmein** [AppDaemon/appdaemon#1240]
I tried using the global lock decorator according to the documenation as follows:

```
import appdaemon.plugins.hass.hassapi as hass

class ValveControl(hass.Hass):
    ...
    @ad.global_lock
    def updateValveStates(self, current):
        ...
```

However, I get the following error:

> ...
>   File "/home/homeassistant/.homeassistant/apps/ValveControl.py", line 6, in <module>
>    class ValveControl(hass.Hass):
>  File "/home/homeassistant/.homeassistant/apps/ValveControl.py", line 84, in ValveControl
>    @ad.global_lock
> NameError: name 'ad' is not defined

What is the correct syntax to use the global lock?

**Comment by ReneTode** [comment]
since app pinning i didnt come accross to anyone that didnt use the default thread settings in AD.
with the default settings locking is rarely needed, so i have never seen anyone actually use it. (and i never used it either)

AD has changed a lot since this has been added, so it very well possible that this is broken.
it also possible that this now only works with new style apps (inherit from adbase, not from a plugin.)

maybe that @Odianosen25 uses it sometimes (hes the only 1 i know that uses non default settings for threading)
so lets see what his opinion is.

in the meantime, its probably wise if you give more background info about how you use AD, and why you want to use locking.

**Comment by Odianosen25** [comment]
@sithmein, you need to import the adbase class to use it. So even though you using hass, you still need to add “import adbase as ad”. The error you getting, is because you don’t import it.

But as @ReneTode has said, it’s something that’s hardly used unless you have some very rare specific use case. You could let us know, then maybe we can advise on more better what to do it.

You should know that using the global lock, affects all of AD, so kindly use with caution.

Regards

**Comment by sithmein** [comment]
Adding the missing import did the trick. May I suggest that the documentation is updated accordingly?

My use case is as follows: I have a `Valve` class with 10 instances (i.e. apps). There is a pump that should turn off once all valves are closed and it should turn back on if at least one valve opens. Because I don't want to have giant if statement for controlling the pump I use a single integer entity and set bits according to the open/closed valves. Once the number is zero the pump can turn off, it it's non-zero it should turn on again. Changing this global entities must be synchronized. Here's the complete method:

```
    @ad.global_lock
    def updateValveStates(self, current):
        state = self.get_state('virtual.valve_states', default = 0)
        if (state == 'unknown'):
            state = 0
        else:
            state = int(state)
        
        if (current > 0):
            state |= (1 << self.number)
        else:
            state &= ~(1 << self.number)
        
        self.set_state('virtual.valve_states', state = state)
```

If there is another way to achieve this without (global) locking I'm all ears.

**Comment by ReneTode** [comment]
i dont think that the lock does do anything here.

you are not modifying any global vars, and thats where the global lock is for.
and you can never lock the state from a sensor.

i would most likely use a something like:
```
    self.valve_list = []
    for app, config in self.app_config.items():
        if "valve" in app:
             self.valve_list.append(config["valve_entity"])
    for valve in self.valve_list:
        self.listen_state(self.check, valve)
        
def check(....):
    state = 0
    for valve in self.valve_list:
        if self.get_state(valve) == "on"
            state += 1
    self.set_state('virtual.valve_states', state = state)
```

this way, if any valve changes state it will always update your sensor.
the state will always be as accurate as possible, because even when 2 valves update at almost the same time, the last time the CB is triggered it checks all states.

any other way could give runs that causes that the last state results in a wrong state.

**Comment by Odianosen25** [comment]
Another option is that all the apps instanciated using the module, pin them to the same thread. That was only 1 callback
Will be ran at any point in time. But this will need good knowledge of the thread processing and setting it up properly so it doesn’t mess up other aspects of AD

**Comment by ReneTode** [comment]
@Odianosen25 please set off your autocorrect ;)

**Comment by sithmein** [comment]
If I understand the `@ad.global_lock` correctly it simply prevents that more than one thread can enter the method. This is exactly what I need since it will be the only place where _virtual.valve_states_ will be modified.
I will think about your suggested approach but having a list of all valves in every valve seems a bit weird from a design point of view.
I don't want to run all valves in a single thread because there are some time-sensitive operations going on.

**Comment by ReneTode** [comment]
> If I understand the @ad.global_lock correctly it simply prevents that more than one thread can enter the method.

i understand it clearly different.
all your apps (app instances) run in different threads, calling different callbacks (allthough they have the same name and the same module) in your case it really doesnt do anything.
every app instance can call that same callback even with the decorator at the same time, if i understand it correctly.

and even when that isnt so, you cannot control the timming from the moment those callbacks are called.
1 statechange can take some microseconds longer then the other to come from HA to AD.

i wouldnt have all valves in every valve, what i suggest is a different class. a seperate app.
which is absolutely not wierd because that app sets the state from a different sensor.

**Comment by Odianosen25** [comment]
@sithmein,

> If I understand the @ad.global_lock correctly it simply prevents that more than one thread can enter the method.

That is true. But if you have time sensitive stuffs going on, I think it’s more reason not to be locking all of AD; as other apps, not even related to this process will also be affected. Also as Rene had said above, it was added for stuffs like self.global_vars, which has no locking mechanism.

Based on what you have said, I will instead have another standalone app, responsible for updating “virtual.valves_state”. Now within that app, I will import the threading module and use it to locally lock access to that piece of code in the standalone app. So something like this 

`
import threading 

def init():
    self._lock = threading.Lock()

def updateValveStates():
    with self._lock:
         <update the sensors>
`

Then in the other app instances for the valves, I will use the self.get_app(“updated_valve_app”) api, get the app for updating and simply pass my data to be updated to it. Since it’s locally locking, only 1 will access it at every point in time. 

You also have options like turning the updating into a service call within AD using the register_service api. As only a single service call can be called at every point in time. And within the service call, queue up the updating within the virtual.valve_state updating app. 

Hope it makes sense?

NB: Using my phone so in case I got something silly in it again 😜

**Comment by sithmein** [comment]
I ended up using a separate app that monitors all valve states: Originally I wanted to avoid having a list of all valves to monitor but it turned out that I need this (or something similar anyway). Therefore I don't need to lock any more.
Nevertheless I have created a PR to update the documentation.

**Comment by ReneTode** [comment]
if you have the valves in app instances from 1 pyscript, then you dont need a list (or better said, you can get the list by looking at the settings from your app instances) (see my example)
