### ISSUE TITLE
Camera full screen when clicked

### ISSUE THREAD

**Issue by DaveDixon** [AppDaemon/appdaemon#1284]
This is a coding question. I have a camera widget on a dashboard. Refreshes every 2 seconds. Works fine. If I click the image, I get I full screen snapshot from the camera. That's okay, but not what I want, really. The trouble is, I can't figure out what triggers to full screen snapshot. I don't see basecamera.js listening for or capturing click events. I'm not seeing it in WidgetBase or anywhere else in dashboard.js.
Suggestions?

**Comment by ReneTode** [comment]
this is something that comes with HA camera intergrations.
you can only help it by using the cam stream directly. (with an iframe widget)

also refreshing a cam widget every 2 seconds isnt the best way in most cases.
using 
stream: "on"
gives you in most cases a better view.
if you use both (stream and a fast refresh) you can end up in trouble.

if you use stream on, then refresh is only needed for cams that sometimes lose connection.

**Comment by DaveDixon** [comment]
Thanks, Rene, for the thorough explanation. If the full-screen is an HA behavior (which isn't how it works on my Lovelace page) that means that either appdaemon is passing the mouse click to HA (which I can't find), or appdaemon is exposing the HA component so it can listen for the mouse click (in basecamera.html?). 

I seem to have bandwidth problems with stream, btw.

**Comment by ReneTode** [comment]
the camera widget puts the stream from HA in an img frame.
you can get that url also directly in a browser.
its like: ha_url/api/camera_proxy/camera.entity?token= ...

as far as i know its possible that event come with that.
we got others who had the same problem, but i never found anything in the widget that explains it.
you can search the widget yourself 1000 times more, but there is no click event in the widget. (if you can find it i could make it optional)
so i can only come to the conclusion that it must come from what provides the stream.

and i dont use HA camerastreams anymore, so i cant test it myself.

did you use the stream without refresh? because both together could explain a bandwidt problem.

**Comment by DaveDixon** [comment]
It makes sense that the component in the img tag manages the event. As you say, there is no click event in the dashboard code - I don't need to search it 1000 times more :).  I could try capturing the onclick in the img tag. But if iframe gives me the flexibility I need, I don't see any reason to keep messing with the camera component.

I didn't use stream and refresh at the same time, btw. 

Thanks again for all your help!

**Comment by ReneTode** [comment]
please close the issue when your satisfied.

**Comment by DaveDixon** [comment]
It was pretty easy to do once I looked at the page in Firefox Developer Tools. 
I created a custom widget, NavCamera, by cloning camera.yaml and the basecamera folder.
basecamera.html looks like this
`<div class="outer-image">
    <a data-bind="attr: {href: img_src}">
        <img class="img-frame" data-bind="attr: {src: img_src}" style="object-fit: contain;"></img>
    </a>
</div>
<h1 class="title" data-bind="text: title, attr: {style: title_style}"></h1>`

So I modifed basenavcamera.html to look like this
`<div class="outer-image">
    <a onclick="navigate_away('OtherDash')">
        <img class="img-frame" data-bind="attr: {src: img_src}" style="object-fit: contain;"></img>
    </a>
</div>
<h1 class="title" data-bind="text: title, attr: {style: title_style}"></h1>`

navigate_away.js is code in my custom skin. It's something I coded for making other components navigable (e.g. NavSensor, a sensor that displays a high-level sensor output but clicks to a dashboard that shows the component sensors). It uses the current window.location.href to determine the correct dashboard for the device and orientation (I have dashboards fine-tuned for each viewing device in either landscape or portrait). In the end, it calls window.location.replace(new_dash). 

In the example above, new_dash = 'OtherDash_pc_landscape?skin=myskin' for my computer screen.

What I don't know is if there's a way to have navcamera inherit everything from camera, overriding only the html. That is, instead of cloning basecamera, is there a way to have a custom widget by creating just navcamera.yaml (I assume it needs this to recognize it as a custom widget) and navcamera.html.

**Comment by ReneTode** [comment]
thx for sharing.
i looked over it a 1000 times and never saw the <a> which off course has a click event.

when you want to have custom widgets there are only 2 options:
1) just a derived widget (yaml file) that uses existing files
2) a complete custom widget, which always needs the js, html and css file in a seperate dir.

but in your case you could just replace the original cam widget by using the same name (renaming the yaml file would already be enough)

i said i would make it optional to configure, but because this is in the html thats a little more difficult.
and because Andrew wants to work on dashboard ill leave it as it is and when another has the trouble, ill point to your solution.

since you use js code from your skin, i guess you are not aware from the recently added option to use custom JS.

every js file that is in the dir config/custom_javascript (youll need to create it) will automaticly be included in your dashboards.

if you have other questions then please visit our discord. youll get a faster answer there.
https://discord.gg/wrdqRK6

**Comment by DaveDixon** [comment]
Yes, I recently noticed the custom_javascript option. That will clean up my skin code a bit. Great enhancement!
