### ISSUE TITLE
Is there a method to register a callback based on the sun's elevation rather than the sunset/sunrise?

### ISSUE THREAD

**Issue by coaxial** [AppDaemon/appdaemon#1291]
I find the `run_at_sun{rise,set}` callbacks unsuitable for my purposes: the sunset time is too late and is after the sun is below the horizon at my location.

So I would like to use the sun elevation values instead because an elevation of 0 matches the time when the sun goes below my horizon.

But how do I setup a callback in AppDaemon based on the sun's elevation value? I'd like it to be like `run_at_sunrise` for instance so I don't have to constantly check the sun elevation in my function, but rather for that function to be called when the sun elevation matches a particular number. I probably missed it in the docs, I couldn't figure out which method that would be.

Thanks

**Comment by ReneTode** [comment]
you can set an offset to run_at_sunrise to let it happen 1 hour before or after sunrise/set

as an alternative (which shouldnt be needed, because its based on the same calculations) you could use a listen_state for the sun elevation sensor in HA.

its not in the docs, because there is no need for workarounds, when you use offset.

**Comment by coaxial** [comment]
The problem with offsetting is that an hour before sunset isn't the same luminosity in summer ça winter. I'm trying to find a way to turn lights on when it gets dark but I can only find values that work for a few weeks at a time before the lights end up turning on when it's too early or too late.

**Comment by ReneTode** [comment]
then elevation will give you the same problem.
i see 2 options:

1) buy/make a light sensor that tells you how dark it is
2) take the offset that you need in winter, and the offset that you need in summer, calculate every week a new offset based on that. and reschedule the run_at_sunrise/set

**Comment by coaxial** [comment]
Thanks, I think I'll go with a light sensor; there are some Zigbee ones for 10$ only online.

**Comment by deviantintegral** [comment]
I'm writing an automation to open a shade based on the sun's elevation. I can't use a generalized light sensor, because the problem is that at certain angles we need to block the sun regardless of how bright the room is. I think a delay would only work near the equator, where sunrise times are less variable?

I have this working by monitoring HA's `sun.sun` entity which provides an elevation. However, I can't use time travel to test the app out. So, supporting elevation (and azimuth?) directly in the app would be a nice improvement.
