### ISSUE TITLE
listen_state callback is not firing with new=0

### ISSUE THREAD

**Issue by deviantintegral** [AppDaemon/appdaemon#1366]
I was tracing why an app wasn't working, and I got down to this fragment:

```python
class WashingMachine(hass.Hass):
    def initialize(self):
        self.log("Starting WashingMachine...")
        self.listen_state(self.notify_done, entity="sensor.washing_machine_smartenergy_metering", new=0.0,
                          immediate=True)

    def notify_done(self, entity, attribute, old, new, kwargs):
        self.log(entity + " changed to " + str(new) + "W")
```

I would expect that this would immediately log if the state is `0` or `0.0`. However, the callback is never called.

If I remove the `new` parameter, it is... but `new` in the callback shows as 0.0:

```
2021-09-29 21:48:27.418317 INFO AppDaemon: Initializing app laundry_room_washer using class WashingMachine from module laundry_room
2021-09-29 21:48:27.434270 INFO laundry_room_washer: Starting WashingMachine...
2021-09-29 21:48:27.440444 INFO laundry_room_washer: sensor.washing_machine_smartenergy_metering changed to 0.0W
```

It doesn't appear that there's any debug logging in `appdaemon.state.State.add_state_callback()` that would help track this down, but a first read doesn't show any obvious bugs. My next step would be to hack in some additional logs, but if there's something I've missed I'd appreciate a pointer.

For now, I can work around this by returning early in the callback.

**Comment by deviantintegral** [comment]
I went to do this, but then got the following hint in the logs:

> TypeError: '>' not supported between instances of 'str' and 'int'

So, it looks like the value is coming in as a string, and not a numeric type. Changing to `new="0.0"` causes the callback to be executed.

This was the first automation where I was attempting to interact with a number. I suppose all states in HA are treated as strings? If so, I wonder if the docs at https://appdaemon.readthedocs.io/en/latest/AD_API_REFERENCE.html#appdaemon.adapi.ADAPI.listen_state could be updated to call that out.

**Comment by Justihar** [comment]
Correct, the value for "new" from an HA entity is always going to be a string but be careful because when using immediate=True, the old value is going to be a None object on the first callback run. Also, when you first start the app, if the washing machine value is 0, your application will think it has stopped even if it wasn't previously running. Another option would be to omit the new parameter from the callback and use something like this in the callback method.

```python
try:
    new = float(new)
except (TypeError, ValueError):
    new = 0.0

if old is None:     # immediate=True
    if new > 0:
        # app just started and machine is already running
    else:
        # app just started and machine is not running

else:
    try:
        old = float(old)
    except (TypeError, ValueError):
        old = 0.0

    if old > 0 and new == 0:
        # machine just turned off
    elif old == 0 and new > 0:
        # machine just turned on
```

Of course, this will make the callback run a lot more frequently, especially considering how often the power value is going to change but you can use the callback for more than just determining if the washing machine has stopped (if that matters to you) and you can compare the old and new values to determine if it actually just stopped or if the app just loaded and it wasn't running to begin with. 

With all of that being said because I just wanted to provide some understanding, you can forget about immediate=True and avoid that complication entirely. In a very simple case where you just want a notification when the washer stops running, immediate=True isn't going to be very useful and will cause errors when trying to compare old and new unless properly handled like I have shown above.

I find it to be very helpful to use self.log(locals()) in the callback method to see the type of data I can expect from the entity as it is changing values.

Hopefully that helps.

-Justin

**Comment by deviantintegral** [comment]
Thanks for the detailed explanation! I had immediate=True for debugging, I filed https://github.com/AppDaemon/appdaemon/pull/1370 to improve the `listen_state()` docs.

**Comment by Odianosen25** [comment]
Will be closing this @deviantintegral, reopen if need be
