### ISSUE TITLE
This project is amazing!

### ISSUE THREAD

**Issue by filmgarage** [AppDaemon/appdaemon#1384]
Thank you very much for creating this developing environment. I was searching for a way to build a clock for my mother who is suffering from the early stages of dementia. I found out it was a great idea to put some sensors in her lights, now I can monitor through Home Assistant that she is still up and running. Getting out of bed etc... She has a lot of trouble remembering the day of the week and keeps asking about it. I coupled the Raspberry Pi that is running HA with a touch screen and now she has a very basic clock telling her what day it is and the day of the week. A simple button on screen makes it possible for her to switch on a light and will tell me that she is still around and doing well. I will include a message every once in a while on the screen suggesting activities through the day! Telling her when the news is on or when it is a nice time for a cup of tea...

![clock](https://user-images.githubusercontent.com/30559371/141192513-73201c7c-8306-4755-9a98-3e82709ad375.jpg)

**Comment by ReneTode** [comment]
nice.

if you add a motion detector below it, it will automaticly tell you that she has been in front of it. then she doesnt need to push the button.

**Comment by filmgarage** [comment]
I try not to scare her away with a lot of 'tech'. For her it would be best to think it is a regular clock. I want to make sure she still feels comfortable in the house... A camera or a motion sensor could very well make her very anxious... If I find a way to make it unnoticeable I will surely consider it.

**Comment by acockburn** [comment]
Thanks for sharing this - it's great to see how people use our software 👍

**Comment by ReneTode** [comment]
@filmgarage its to bad that you have an RPI with a screen and not a tablet, because then you could use fully kiosk and the cam and motion from that.
but i get your point.
if the RPI is on the back on the screen you could try adding a sound sensor. but you would need to work on it, and then she could notice.
another option is to make a more advanced design, with mote options (like sound detection) where she doesnt see you, and then at the moment that you are satisfied, just switch the new design with the old one.
a pir sensor behind the screen looking sideways could also work, depending on where you placed it.

if you want im always available on our discord to discuss more options.
