### ISSUE TITLE
[4.2.0] set_state(state=something) does not turn on/off the switch

### ISSUE THREAD

**Issue by prof7bit** [AppDaemon/appdaemon#1451]
I am using it with home assistant plugin. Version seems to be 4.2.0

```python
    def initialize(self):
        self.adapi = self.get_ad_api()
        self.switch_speisekammer = self.adapi.get_entity("switch.speisekammer")
        self.sens_speisekammer = self.adapi.get_entity("binary_sensor.speisekammer")
        self.sens_speisekammer.listen_state(self.on_tuer_speisekammer)
```
I want to copy the state of the door sensor to the shelly switch that controls the light. After reading some API example I figured out that the following should do the trick:

```python
    def on_tuer_speisekammer(self, entity, attribute, old, new, kwargs):
        if attribute == "state":
            self.switch_speisekammer.set_state(state=new)
```

The method will be called when I open the door and `new` contains "on" or "off" but it does not change the switch state in any way, it also does not produce any error logs, it just does nothing. However if I am doing it this way:

```python
    def on_tuer_speisekammer(self, entity, attribute, old, new, kwargs):
        if attribute == "state":
            if new == "on":
                self.switch_speisekammer.set_turn_on()
            else:
                self.switch_speisekammer.set_turn_off()
```
Then it works flawlessly.

But I want to avoid this if/else, instead of two different functions I would rather have one function and pass the state as an argument to unclutter the code. From reading the docs the set_state() method should do exactly what I want, but it doesn't. So now I seem to need a helper function or need to monkeypatch the Entity class to have a generic turn() method that combines both methods into one.

Is this a bug?

**Comment by ReneTode** [comment]
no it isnt.
setting the state from an entity is something else as doing it through a service.
i dont know if there is already a call_service for the new entity class, but if so they you should use that.

**Comment by ReneTode** [comment]
and if there isnt (as someone just told me), then you can use the normal call_service function.
```
self.adapi.call_service("switch/turn_{}".format(new), entity_id="switch_speisekammer")
```

**Comment by prof7bit** [comment]
> no it isnt. setting the state from an entity is something else as doing it through a service. i dont know if there is already a call_service for the new entity class, but if so they you should use that.

This is a little bit confusing, from the view of an ordinary user it is not obvious how a "service" is involved (or needs to be involved) if I just change the state attribute as opposed to calling a helper method (turn_on()) that totally looks like it would have the purpose to do the same.

Moreover there are examples in the documentation that are using set_state(state="on") method to turn on the light.

I don't understand why this should not work. If the state attribute cannot be controlled with set_state then maybe it should not even be possible to pass it into the method, and maybe the method should not be called set_state() if it is not possible to set the state, this is totally confusing.

but the more obvious fix would probably to make it behave as expected (setting the state just does exactly that: changing the state). If it needs to run "services" to accomplish this it should automatically run them to abstract this implementation detail away from the user.

**Comment by prof7bit** [comment]
I would probably have gone an even more rigorous and pythonic way when designing the entity class and would not have used any setters and getters at all and instead would exposed all attributes as native attributes of the class and hooked hidden setters/getters into them to do the dirty work that is needed to interact with the underlying home automation method calls and services:

```python
    # turn on the light
    self.switch_speisekammer.state = "on"
````
This would be a much nicer API

**Comment by Justihar** [comment]
Think of set_state as setting a variable and call_service as calling a function. Also the functionality is no different in HA. set_state is typically for sensors and call_service is typically for integrations. If you go into HA developer tools, you can set a state on a switch to “on” and nothing happens unless you call the service. It’s no different. Also, all AD apps are written in Python. You cannot really abstract this functionality away from the app developer. HA doesn’t even abstract this away from its uses.

**Comment by Justihar** [comment]
If all you’re trying to do is turn something on and off, sure, but AD allows way more complicated stuff. I’m sorry but the change you are suggesting will not happen. If you want something to turn on and off by using a set_state, then create a listen_state that listens to an entity and calls the service to turn that thing on/off. The great thing about AD is you can make most implementations that your want yourself.

**Comment by prof7bit** [comment]
> you cannot really abstract this functionality away

Of course you can abstract it away. Especially in Python you can do crazy things to wrap even the most ugly and illogical API into a nice pythonic abstraction that is a real pleasure to use.

**Comment by ReneTode** [comment]
ok. im going to be a bit rude.

if you want set_state to work then just stop using entities from home assistant.
i you create entities in appdaemon then you can use set_state to change the state from the entity.
it will change the state, but it wont turn it on, because thats what the service does.

HA doesnt allow changing state from entities, unless you do it through a service (except when its a sensor you create from AD, or an entity that you create and control from AD into HA)

ordinairy users are supposed to create automations in HA.
in AD the people are expected to understand a bit more.

so to be short: with set_state you CAN change the state from an entity, but you NEED a service to control a device.

**Comment by prof7bit** [comment]
> I’m sorry but the change you are suggesting will not happen.

What is the rationale behind keeping a dysfunctional set_state() method around that cannot be used in any meaningful way instead of just implementing it the way the user expects it to work and as it is already documented (currently the documentation is showing an example that does not work)?

I mean i can totally wrap this API into something more usable myself, but I am trying to understand why you did not use this opportunity when you designed the new entity class in recent versions, you could have abstracted away all these complicated unexpected low level implementation details behind a nice and easy to use intuitive API, in my opinion you missed a huge opportunity here.

What is for example the rationale of not being able to just say `some_entity.state = "on"` or maybe even `some_entity.state = True` instead of forcing people to use some crazy string manipulation to construct a service call to do the same? i don't get it.

**Comment by prof7bit** [comment]
> HA doesnt allow changing state from entities, unless you do it through a service (except when its a sensor you create from AD, or an entity that you create and control from AD into HA)

Then I would hook into the setting of that attribute to call the service instead if HA needs it that way to accomplish the state change. Easy fix. Setting a state without actually really setting it does not make any sense. If HA allows for such nonsensical usage (allowing a read-only attribute to be written) you don't need to make this bug accessible in your API, instead you could design the API so that it just works as expected and allow the attribute to be written the proper working way.

**Comment by Justihar** [comment]
Can you please explain in technical detail how AD is supposed to know that an entity is meant to have a service called upon it?  This would have to work universally across ALL entities which have varying attributes. This is essentially what you’re asking for.

From: Bernd K. ***@***.***>
Date: Saturday, January 8, 2022 at 4:34 AM
To: AppDaemon/appdaemon ***@***.***>
Cc: Justihar ***@***.***>, Comment ***@***.***>
Subject: Re: [AppDaemon/appdaemon] [4.2.0] set_state(state=something) does not turn on/off the switch (Issue #1451)

HA doesnt allow changing state from entities, unless you do it through a service (except when its a sensor you create from AD, or an entity that you create and control from AD into HA)

Then I would hook into the setting of that attribute to call the service instead if HA needs it that way to accomplish the state change. Easy fix. Setting a state without actually really setting it does not make any sense. If HA allows for such nonsensical usage (allowing a read-only attribute to be written) you don't need to make this bug accessible in your API, instead you could design the API so that it just works as expected and allow the attribute to be written the proper working way.

**Comment by prof7bit** [comment]
Maybe the same way the lovelace UI knows how to connect the GUI switch if you place a switch or light entity onto an entity card. Somehow it seems to be able to determine how to turn it on and off.

**Comment by Justihar** [comment]
But how is AD supposed to know in a universal way what service calls an entity can have called upon it? These are integration details that are not shared outside of HA. Lovelace is part of HA and although I'm not a heavy use of the front-end, I don't believe there are any elements (other than the dev tools) of the HA front-end that allows you specifically to perform a set_state() type operation. Even setting the state of an input_boolean, input_select, etc are service calls. But even if all of these integration details were available to AD and we could implement such a thing, would we want to try and put all of that under set_state?  Absolutely not and for many reasons.

What you are asking for is a set_state operation of an entity to turn it on and off. You can do this as I have described however it is not something I ever foresee being added to the core of AD as it would be very hacky and unreliable.

AD specifically implemented the turn_on() and turn_off() helper methods within the hass API to make it easier for you to do this, so at this point, I am failing to see what the actual problem is other than you are unhappy with the implementation of set_state, which has for the most part been unchanged, accepted and used by the AD community for many years. Setting the state of an entity is not the same thing as calling a service so bundling those two things together wouldn't make sense at all.

**Comment by prof7bit** [comment]
> AD specifically implemented the turn_on() and turn_off() helper methods within the hass API to make it easier for you to do this,

As far as the turn_xxx() methods are concerned It would have been even easier if you had made a generic turn(state) method instead of exposing these as 2 separate methods (and then maybe even let it also accept a boolean instead of a string, it would clean up the needed code a lot when doing more complex boolean logic to control the state of a bunch of switches), probably then I would not even had opened this issue because then I probably would not even have tried to use set_state().

Turning on and off switches and lights is probably one of the most primary things most people will want to achieve and the better the API for doing this the shorter and more concise the code that uses it will become.

And at least you could write a big warning into the documentation of set_state() that this will not do what one might expect it to do (and maybe change the example code as well or document it accordingly because this code strongly suggests that one can simply use that method to control the light).

**Comment by Justihar** [comment]
I just had to revisit the entity.py file, which does indeed have a turn_on and turn_off method if you are using the Entity class but in your case probably not the best to use but you can use any of these. Not really sure how much more shorter or concise you want it. I prefer using service_calls of these.

```
entity = get_entity(entity_id)
entity.turn_on()
entity.turn_off()
```
```
control_entity(self, entity_id, command):
    method = getattr(self, f"turn_{command}")
    method(entity_id)
```

```
control_entity(self, entity_id, command):
    self.call_service(f"switch/turn_{command}", entity_id=entity_id)
```

**Comment by prof7bit** [comment]
I am currently in the process of making my own helper functions similar to the ones above to be able to simplify my code. Probably I am going to monkeypatch the Entity class to add some __getattr__/__setattr__ voodoo to expose the state as a read/write boolean property and maybe consequently do the same with all other attributes as well.

**Comment by ReneTode** [comment]
> And at least you could write a big warning into the documentation of set_state() that this will not do what one might expect it to do (and maybe change the example code as well or document it accordingly because this code strongly suggests that one can simply use that method to control the light).

i already tried to explain to you that set_state does exactly what it says, it sets the state.
it isnt useless, it isnt obsolete, because its the only thing you can use to change the state from a sensor.

home assistant has services for turn on and turn off.
and AD was build to serve homeassistant. maybe it could have been rewritten afterwards to just turn, but that would just add another function, because you can just remove the old functions.
and because you can also do it with service_call there is no need to change it.

lovelace calls services (they are written in the GUI in JS) just like HAdashboard calls services (written in the GUI in JS)
if you write an automation in HA you call services, you dont use set_state

and you cant say: hey lets do everything with set_state, because then AD would need to interprete EVERY state and decide when to call which service. which is impossible, because you can create an entity like my_switch_type.something and then call the service like call_service("my_namespace/what_to_do", entity_id = "my_switch_type.something")

how would AD know that my_switch_type needs that service, when i just use set_state??

so yes again i say: SET_STATE WORKS AND IT DOES WHAT IT NEEDS TO DO, IT CHANGES THE STATE!
and it is very usefull for a lot of things (like changing a sensor state)
if you want a light to turn on (and not just the state in AD/HA to change) then you NEED a SERVICE!

**Comment by ReneTode** [comment]
and off course you can do for yourself:
if namespace == "hass" and entity_type == "switch" and state == "on":
    self.call_service("switch/turn_on, entity_id = entity, namespace=="hass")
    
and overwrite_set_state
but then you will need to add EVERY possible service there is, and keep adding them for all types you create yourself.

**Comment by prof7bit** [comment]
> > And at least you could write a big warning into the documentation of set_state() that this will not do what one might expect it to do (and maybe change the example code as well or document it accordingly because this code strongly suggests that one can simply use that method to control the light).
> 
> i already tried to explain to you that set_state does exactly what it says, it sets the state.

The doumentation contains stuff like the following

```
>>> self.my_enitity = self.get_entity("light.living_room")

Update the state of an entity.

>>> self.my_enitity.set_state(state="off")
```

And this implies that this is a possible way to turn off the light in the living room by setting its state to "off". 

Maybe after working with HA for too many years the understanding what "changing the state" actually means (or used to mean in **any other** context other than this one particular oddity in home assistant) slightly changes its meaning and then updating the state of somethiing no longer actually updates the state, but from my understanding a switch has two states: on and off and if I have an API that wrapps this switch and it has a method to to change the state then I expect it do do exactly that: change the state, no matter what complicated stuff it internally has to do to achieve this if the underlying thing it wraps has complicated procedures to change its state. As the user of the API I don't want to care about this. It is implementation detail.

This in my opinion is what a good API should do for the user: abstract away the ugly implementation details and have methods and properties that actually do what their name implies.

Probably we both have a different opinions about API design.

**Comment by ReneTode** [comment]
no your problem is that you see 1 thing where there are 2 things:
1) is a device
2) is a piece of code, a set of vars in the memory from a device that controls other devices.

1 is the actual thing, the other is a reprensentation from the actual thing.
you can still change the state from the representation, but you will also need a piece of code that changes the actual device.
that piece of code is called a service and it needs to be called somehow.

1 other thing why you need set_state beside the services is that the representation from the device can get off, so you want to change the state from the representation, but not trigger the actual code that changes the device. (questions like that came up hundreds of time, in a lot of cases with 433 mhz devices)

a switch hardware has 2 states, but the entity can have more, for example "unavailable"

but i say you are right that the examples are wrong.
it should have been an example from a sensor.

 so lets ask @odianosen if he will change the docs to something like:
 ```
 >>> self.my_enitity = self.get_entity("sensor.livingroom")

Update the state of an entity.

>>> self.my_enitity.set_state(state="occupied")
```


and if you think the API from AD is no good API, then you are free to develope your own, change it, or just dont use it.
but if you start telling developers from a populair program that theit program is no good, then dont expect to get an ear from them.

> Probably we both have a different opinions about API design.

i dont have the arrogance to tell others what is good and what isnt good.
im just a former dev, that helped out thousands of people. and i know how AD is realised, where it came from and where it goes. and you cant just change commands from a program with hundredthousand users. even if you can think of better ways its not always possible just to start with a clean slate.

**Comment by prof7bit** [comment]
> no your problem is that you see 1 thing where there are 2 things:
> 
>     1. is a device
> 
>     2. is a piece of code, a set of vars in the memory from a device that controls other devices.

This is the problem, it seems we have a strongly differing opinion about what the relationship of these 2 things should be:

In my opinion the states of the device and the states of that wrapping piece of code should always be in sync, at all times and under all circumstances, the internal implementation should make sure that this is always true. Otherwise i consider it broken or flawed API design.

> change the docs to something like:
>
>        self.my_enitity = self.get_entity("sensor.livingroom")
>
>        Update the state of an entity.
>
>        self.my_enitity.set_state(state="occupied")

Again this does not make any sense to me because a sensor, by its very definition, is generating this state on its own, it should be read-only and not be able to set a different state than that it actually has from the outside.

Unless of course you are talking about the actual implementation of a sensor device representation that would have **internal** (or private) methods to update its state, but they should not ever be meant to be used from the outside. Since Python does not have private members one would typically use naming conventions to mark these methods as internal or private, not part of the public API.

**Comment by ReneTode** [comment]
> In my opinion the states of the device and the states of that wrapping piece of code should always be in sync, at all times and under all circumstances, the internal implementation should make sure that this is always true. Otherwise i consider it broken or flawed API design.

yeah, that is the wish from everybody.
but i welcome you to the real world. where doorsensors sometime only send "open" but not "closed"
so that people want to set "closed" themselves
or where a 433 mhz switch sometimes not responds, and the device is out of sync and the program has NO way to check if it is in sink, so the user wants to correct the program.

> Again this does not make any sense to me because a sensor, by its very definition, is generating this state on its own, it should be read-only and not be able to set a different state than that it actually has from the outside.

and how would you create a time sensor? or a sensor that tells if you are sleeping?
a sensor is not always representing a physical device. its in a lot of cases just representing a state from anything.
without set state, you wont be able to create sensors.

and im not talking about internal methods, but sensors that you want to present in a frontend.

**Comment by ReneTode** [comment]
1 other thing.
in AD users create and maintain entities themself.
you can create a switch entity based on mqtt events for example.
how would i change the state from that switch from unavailable to on or off, if i cant set the state based on what mqtt presents?

how are you able to create and maintain entities, when you are unable to change their state??

**Comment by Odianosen25** [comment]
Please will be closing this thread, reopen if needed @prof7bit as I don't think we will be supporting the ability to use `set_state` to control a device. I believe my colleagues have explained enough on that.

Kind regards
