### ISSUE TITLE
Scheduled tasks are offset -1 hour after time moved forward by 1-hour 

### ISSUE THREAD

**Issue by Justihar** [AppDaemon/appdaemon#1485]
Let me know if you guys need some help with testing any changes.  Thanks!

**Comment by acockburn** [comment]
Yes, I had this too - this whole area is a nightmare, time is hard :(

When I first built AD I had it restart all apps when a change from DST or the reverse happened and it worked perfectly. Trying to figure out the change and rewrite timestamps sounds easy, but there are so many corner cases its impossible to get it right for every circumstance. Having said that, I'm sure there is a bug here, problem is I only get to test it once a year. Even time travel doesn't seem to help as reality is different in this case with different code paths. At this point I might just revert to restarting all apps, although I changed it in the first place because it was upsetting some people.

**Comment by acockburn** [comment]
This seems to be fixed in the current dev - lets see what happens on November ... closing until then.

**Comment by theastropath** [comment]
The time fell back on Sunday (yesterday) and my scheduled tasks all ran an hour early, as though the time change was not detected.  I thought it might self-correct on the *next* scheduled event, but it seems things were still running early this morning.

I've rebooted my AppDaemon now and expect it should have corrected itself.

I'm running through the AppDaemon Home Assistant Add-on, which *I believe* is running 4.4.1, which (I think?) should include the fix mentioned earlier in this thread.
