### ISSUE TITLE
[Feature Proposal]: `None` as a valid handle for cancel methods

### ISSUE THREAD

**Issue by mementum** [AppDaemon/appdaemon#1487]
Quite often it is very handy to keep handles to timers or state listeners in a `defaultdict`

```python
import hassapi as hass
from collections import defaultdict
...
...
class Hass(hass.Hass):
    def initialize(self):
        self.handles = defaultdict(lambda: None)
...
...
    def cancel_something(self, key):
        self.cancel_timer(self.handles[key])
```

This is because it is not known when entities will become available, which may happen at anytime during the lifecycle of the application. In this case the app would be managing several entities of the same class (for example: shutters)

Currently `None` is accepted by `cancel_timer` and `cancel_listen_state`, and probably others, but a warning is generated in the logs, indicating that a non-valid handle was passed.

The proposal is to make `None` an officially accepted value (which of course cancels nothing) and generates no warning.

Just an idea.

Best regards

**Comment by Odianosen25** [comment]
@mementum,

Get your point, but this can easily be avoided by first checking if the value is None in the first place. Besides if we allow that, it could mask other issues a user might have missed for example maybe they thought they setting up the timer when actually it’s not and it will be None and it will just go thru. Or they mistakenly overriding a handler without even know and it will be invisible.

The entire idea is to give the user a true state what their app is doing, and why it will not be actually good to do what you requesting.

Your issue can easily be fixed with 2 lines of code at most, to check if it’s None and not cancel. Than potentially masking errors in users code, that could make the app malfunction if that makes sense.

regards

**Comment by mementum** [comment]
Just an idea, but I also see that some users may be puzzled or run into some quirk.
