### ISSUE TITLE
[performance] async callbacks, ad.app_lock, and "HASS: Disconnected from Home Assistant, retrying in 5 seconds"

### ISSUE THREAD

**Issue by dgrnbrg** [AppDaemon/appdaemon#1625]
Hello, I have a several applications I've written that are pinned and use `@ad.app_lock` to protect multiple pieces of shared state. I'm using the appdaemon add-on with homeassistant.

These applications need to `listen_event` to very high throughput events, like `call_service` (a use case similar to Adaptive Lighting's "take control" mode) and a custom event containing every BLE packet around my home.

When I don't use async callbacks, my app's state remains consistent through the many callbacks. However, the queue size grows and grows, which spams the logs, and is bad b/c I can't keep up with the load.

When I change the app to use async callbacks, I never see the queue size grow on the async thread, but I can't use the locking decorator (and so I can get bad states in the app), and I see every few minutes the message "HASS: Disconnected from Home Assistant, retrying in 5 seconds", after which all the apps get reloaded. Could this be due to the HASS subscription queue overflowing?

For both of my use cases, I early-return from the event listener callback if the event doesn't match, which is the case for 99.9% of events. I think it should only be a couple milliseconds for these early returns, so I think everything should work.

Could you help me with some advice to:
1. Process all the events I'm recieving
2. Suggest how to manage locking

**Comment by Justihar** [comment]
You may need to elaborate on "to protect multiple pieces of shared state" as you don't need to pin an app or use locking for an app to hold state in a class variable. If you need to share state across different apps, I'd recommend you use a persistent namespace and store state in entities.

Are you breaking up your apps to minimize the amount of events that each app is handling? If not, you'll want to do that.

As far as the early return, as mentioned above, you can filter events so that only the events you want handled are processed by the callback method. I understand this may not always be possible but the more you can filter an event, the less time your app has to spend doing evaluation.

**Comment by dgrnbrg** [comment]
I've tried to format my response to save you time if you don't want to read it all :) Thank you for you help, and for this awesome system!

I've been building a ton of stuff with AppDaemon. Once I get it fully debugged, I plan to share these things I made (which I think are pretty great automations).

## Difficulties in minimizing the number of events processed

The issue I have with minimizing the events is this:
- For the app which needs to process the `call_service` events, I would need to filter on whether a key in the `data` map contains a list, which contains a particular element. I thought I can only filter on the top-level keys in the event that have constant values.
- For the app which needs to process the bluetooth events, I need to do a calculation first to determine whether the address matters or not. So, I need to process every single event so that I can populate the `known_addr_cache` (I wrote more about it below)

## Early return that doesn't seem to be fast enough

For the early return, it looks like this, but it still seems to be unable to keep up with the rate of events:
```
    async def ble_tracker_cb(self, event_name, data, kwargs):
        matched_device = 'none'
        if data['addr'] in self.known_addr_cache:
            matched_device = self.known_addr_cache[data['addr']]
        else:
            matched_device = do_matching_computation(data)
            self.known_addr_cache[data['addr']] = matched_device
        if matched_device == 'none':
            return
        # proceed to do process the matched device
```

## Detailed description of the shared state within a single app

Here's the part of my init function that sets up the state of the tracking system. Each of these local variables are updated in the app from multiple callbacks. So, these 6 pieces of shared state (within the app) should only have 1 callback interact with them at a time. There are 2 callbacks that listen to state/event changes in HomeAssistant, and those callbacks each create additional callbacks via `run_in`.

```python
    def initialize(self):
        self.known_addr_cache = {}
        self.device_in_room = defaultdict(lambda: 'unknown')
        self.active_device_by_person = defaultdict(lambda: 'unknown')
        self.expiry_timers = {}
        self.away_tracker_state = {}
        self.away_tracker_pending_arrivals = {}
```

Then, I set up a few callbacks:
```
        self.listen_event(self.ble_tracker_cb, "esphome.ble_tracking_beacon")
        for cfg in self.args['away_trackers']:
            #self.log(f"configuring away tracker {cfg}")
            person = cfg['person']
            tracker = cfg['tracker']
            self.listen_state(self.away_tracker_cb, tracker, person=person)
```

The `ble_tracker_cb` first checks the `known_addr_cache`, and if the address isn't in the cache, it does a computation to identify the device.

Each identified device does a big, complicated signal processing step (that takes 50ms). It also does the following to track when we haven't seen the device after a while:

```
        await self.tracking_resolve(matched_device) # <========= this is the complex signal processing step
        if matched_device in self.expiry_timers:
            await self.cancel_timer(self.expiry_timers[matched_device])
        self.expiry_timers[matched_device] = await self.run_in(self.device_expiry, delay=self.tracking_window.total_seconds(), expiring_device = matched_device)
```

The `away_tracker_cb` has a similar idiom with a timer that runs after a delay under certain conditions.

**Comment by Justihar** [comment]
Ok, I will try to address this the best I can but I want to start with mentioning that a single app can only process a single callback at a time. If you have a single `listen_event()` that is going to be very busy, consider moving any other `listen_event()` or `listen_state()` callbacks to another app so they can run in their own thread. If you need to share state between those 2 apps then you should either store the data in an entity such as a sensor entity within the default (typically HA) namespace or create a persistent namespace in AD and store the state in there. Also understand that if you have `run_in()` callbacks within the same app, their execution is going to hold up the callbacks that are processing your already very busy `listen_event()` callbacks. You can also create other apps that replicate the function of your `run_in()` callbacks and have them listen to state changes of entities that are updated from your main app. This way, the work being handled within your `run_in()` callbacks can run in their own thread. 

The first piece of code you shared isn't very helpful because we're not seeing what `do_matching_computation()` does and we are also not seeing how you are using async. I am not sure how much experience you have with async but I often see it being used improperly, especially in AD, and I am guilty of it myself.

Although it may only be a couple callbacks, the loop creating listeners has the potential to create many listeners that need to execute many callbacks..... and at this point, I am starting to see a trend.... too many (busy) callbacks in a single app.

The last snippet of code doesn't really take advantage of async in a meaningful way. There are many methods in AD that can be executed synchronously but on the backend are processed asynchronously and pushed to the event loop. I don't think there is any benefit to running `self.cancel_timer()` or `self.run_in()` with await. In fact, it might actually slow down execution because those methods might typically be pushed into the event loop (`create_task()`) without waiting for a response.

**Comment by Justihar** [comment]
There is a reason I switched my home automation system to run on a regular computer a number of years ago. The Raspberry Pi is a neat..... toy....... it is good to get started but we have to maintain a reasonable level of expectations as far as its capabilities.

**Comment by dgrnbrg** [comment]
I agree with you, but I also want my code to be usable by others who only have a raspberry pi.

But **great news**! I've managed to get it running with the optimization on a Raspberry Pi 4, and now it is able to easily keep up with the rate of events.

I really hope that we can merge #1626, and then I can ping Frenck to release the addon, and then the speedups (and new API) will be useable by everyone :)

**Comment by acockburn** [comment]
Looking at merging #1626 so closing this
