### ISSUE TITLE
[development] Streamline Github labels

### ISSUE THREAD

**Issue by mion00** [AppDaemon/appdaemon#1688]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Your feature request

Clarify the usage of labels in this repository:
- What is the difference between `docs` and `docs-needed`? Maybe keep only one named `documentation`?
- is `inactive` needed? Now that we are introducing the Github action it automatically uses `stale`, so maybe we should only use the latter?
- `wait-response`, `Needs Research` and `question`. Aren't they all about an issue pending further information from the author? Shouldn't we use a single label for this?
- Maybe it could be useful to add a description to the labels that are missing one?

### Example
Just as a reference, this are the standard labels that nowadays Github automatically creates in new projects:

![Screenshot from 2023-03-04 08-54-24](https://user-images.githubusercontent.com/4510647/222884183-4cfe78b9-e600-42a9-9c7b-97089dce136e.png)

**Comment by acockburn** [comment]
The labels we have were inherited from the HASS repository. I took an initial review of them yesterday and cut a few. To your specific points:

`docs` vs` docs-needed` is a subtle distinction but important. Docs means I or the team need to fix something in docs - this could be renamed documentation and changed to blue to match the standard tags. docs_needed is what I use for Pull requests in which the author didn't;t contribute docs. My policy is not to accept PRs that require docs unless the author does the documentation. This label denotes that they have provided a PR without docs, and I have asked for them. If there is no response, this should be aged out on the same schedule as PRs with out standing questions that are not responded too, e.g. the short period.

`wait_rsponse` and `question` are arguably the same thing and could be merged, but "research_needed` I am using for issues that may or may not be bugs but require research. Again, arguably not necessary as it can be labeled a bug until proven otherwise.

Some of the others I just don't see ever using. If something is invalid I'll just close it, if I won't fix something I'll just close it. If it's a duplicate I'll just close it. If there was a larger team with more folks working on triage they could be useful I suppose.

**Comment by acockburn** [comment]
I took another pass and harmonised them some more and updated the stale tracker action to match.
