### ISSUE TITLE
Callback signature validation fails for (*args, **kwargs)

### ISSUE THREAD

**Issue by efficiosoft** [AppDaemon/appdaemon#462]
Hi,

The new sanity check fails for callbacks that use wildcard positional/keyword arguments.

I saw something like

    cb = lambda *a, **kw: some_func_without_args()
    self.run_in(cb, 1)

failing with

    Incorrect signature type for callback <lambda>(), should be f(self, kwargs) - discarding

I'd propose to skip the sanity check if wildcard arguments are involved in any way, because people using them are usually able to read a traceback.

**Comment by acockburn** [comment]
OK, I can look into that. Curious why you are doing the above - is it simply a way to call the callback when you don;t care at all about the supplied parameters?

**Comment by efficiosoft** [comment]
Yeah, I sometimes have existing functions that are not written to be used as callback for a specific scheduling or state listener procedure but need to be invoked as a callback. Of course, I could as well just make the ``lambda`` accept the expected parameters, but wouldn't use them after all.

I was simply confused to see a callback not being accepted anymore in the 4.x version that would actually work just fine. Whether that's something to be supported is arguable of course, but what seems to be a valid reason for supporting it is compatibility with decorators.

Just out of curiosity, what is the purpose of this check at all? I mean, a ``TypeError`` is raised when a signature is incompatible, and AD has to cope with exceptions in user code anyway, so why not just show them the traceback and, maybe additionally, the expected signature, but only when there really was a ``TypeError``?

**Comment by ReneTode** [comment]
the docs clearly state that schedulars expect callbacks to have a callback that is setup in a certain way. just like listeners.

so dont call a normal function, but create a callback.
you can always call the normal function from the callback you create.

so not:
```
  self.run_in(cb,1)
def cb():
  #do something 
```
but
```
  self.run_in(self.cb_start,1)
def cb_start(self, kwargs):
  cb()
def cb():
  #do something 
```

**Comment by efficiosoft** [comment]
@ReneTode Thanks, but that's not the point I'm making.

In fact, the ``cb`` from my example **does** accept the parameters mentioned in the docs, is fully compliant and would execute just fine. That's what wildcard arguments are made for. It's just that AD's sanity check fails. But instead of stating "Your docs are wrong!" I try to disscuss with you what can be done to **improve** the UX.

Best regards
Robert

**Comment by ReneTode** [comment]
i think the docs are right.
if you follow the docs there is no problem.

if you do it the way i showed there is also no problem (because its according to the docs)
its when you do it your way that the sanity check tells you its not the way that is expected.

**Comment by efficiosoft** [comment]
> if you do it the way i showed there is also no problem (because its according to the docs)
its when you do it your way that the sanity check tells you its not the way that is expected.

With that argument, you make wildcard parameters obsolete. Their purpose is to match anything, and if you know Python a bit you must recognize that there are very real use cases for them to be used. It's like when a TV manufacturer would forbid you to use universally programmable IR remotes, even if they do support the TV model.

**Comment by efficiosoft** [comment]
@ReneTode Let's not continue to talk about whether it can be done with exactly named parameters or not. I made a concrete suggestion above:

> Just out of curiosity, what is the purpose of this check at all? I mean, a TypeError is raised when a signature is incompatible, and AD has to cope with exceptions in user code anyway, so why not just show them the traceback and, maybe additionally, the expected signature, but only when there really was a TypeError?

That would give users the traceback with line numbers to look at, together with the correct signature that was expected.

**Comment by efficiosoft** [comment]
Would probably even be the only reasonable way to do it, since you don't have to reinvent the signature checking built right into Python anyway. And if you fear the traceback is to complicated for an average user... well there's still the hint with the expected signature.

**Comment by ReneTode** [comment]
> With that argument, you make wildcard parameters obsolete. Their purpose is to match anything, and if you know Python a bit you must recognize that there are very real use cases for them to be used. It's like when a TV manufacturer would forbid you to use universally programmable IR remotes, even if they do support the TV model.

you still can use kwargs with the callback.
a tv manufacturer wont forbid you to use it, but he will tell you that if you got behaviour you dont want, that he doesnt supoort that way of using the TV and if you want to avoid the problem you got with the universal remote, you need to use the one they deliver. he will never consider thinking about a solution for your problem with the general remote.

you dont know how many times i have seen errors on the forum, where i need to tell people that they have a callback that is configured the wrong way. so allthough andrew did put this in i am very glad with it, because it will save me at least quite a few questions.

i havent tested it, but i think the main problem is that you dont have "self" in it.
```
  self.run_in(self.cb_start,1, any_var_you_like = any_value)
def cb_start(self, kwargs):
  cb(kwargs["any_var_you_like"])
def cb(var):
  self.log(var)
```
should still give you any_value.

**Comment by efficiosoft** [comment]
Wildcard parameters and the ``kwargs`` taken by the callbacks are completely different things that serve different purposes.

Anyway, did you read what I actually suggested in my first reply and again quoted in the previous one? Because you don't comment on it at all.

**Comment by TD22057** [comment]
I just ran into something similar to this as well.  I had written my callback like this:
```
def update_lights(self, turn_on):
```
and then called like this:
```
self.run_in(self.update_lights, self.home_delay, turn_on=False)
```
which I expected to work fine since kwargs are normally done as **kwargs in python.  But it failed - the argument is `kwargs`, not `**kwargs`.   I realize the docs are clear, but I kwargs in python are generally always passed as **kwargs - that's how they're used in the standard library so that's what I expected the API to be.  I ended up having to write another wrapper like this to get things to work:

```
def update_lights_cb(self, kwargs):
   self.update_lights(kwargs["turn_on"])

def update_lights(self, turn_on):
   ...
```

Passing a dict instead of the actual arguments makes regular functions harder to call, standard library (and external library) functions impossible to call without a wrapper (which is extra code for no reason), it's more work to document everything since the calling arguments are not in the signature, and it's not the way kwargs are normally used in python.  I did a search on 'python kwargs' and every page is assuming they are being used as **kwargs so it's a pretty standard idiom.

I'd like to make a suggestion to consider changing this for the version 4 release and pass **kwargs as the argument to callbacks.

**Comment by acockburn** [comment]
Yes, I'm starting to think this makes sense, although this will break a lot of apps, which gives me pause.

**Comment by efficiosoft** [comment]
I also think that this is a major design flaw (maybe even the biggest) of AppDaemon.
Changing it would break backwards compatibility, but as always with these kinds of changes we need to think about whether to carry old stuff along or drop it to allow evolution.


BTW, Python would then even check if a callback's signature matches the way it was registered for free without having to implement anything custom.

**Comment by TD22057** [comment]
I'm not sure it's a good solution, but if you want to keep the single variable option open, you could have a flag on the class that says old or new callbacks.  Not sure which way the default should be.  Something like:
```
class Foo(hass.Hass):
   old_style_cb = True
   ...
```
and then switch on that in the dispatcher with something like:
```
if self.old_style_cb:
   callback(kwargs)
else:
   callbak(**kwargs)
```

**Comment by efficiosoft** [comment]
Probably worth for a migration period, but I would definitely use real keyword arguments by default, because people wouldn't switch over without a bit of force...

When upgrading from 3.x to 4.x, it should IMHO be acceptable for users to turn on a compatibility setting if they don't want to upgrade their apps yet. I mean, it's a major version change, which should justify API changes.

But after all, this is a more involved change, also greatly affecting the docs, and @acockburn will have the most complete view on all the internals affected.

**Comment by acockburn** [comment]
The callbacks and docs will be relatively easy, hard part is that I also use kwargs to pass hidden variables back and forth so would need some care around that

**Comment by ReneTode** [comment]
i am sorry but i got a different view. (and also a big stake in it, because such a breaking change would give me hours of work)
i really dont see the point, other then that people would like things to be as they expect it elsewhere.

this:
```
def update_lights_cb(self, kwargs):
   self.update_lights(kwargs["turn_on"])

def update_lights(self, turn_on):
```
is in my eyes quite stupid.
why would you want a CB that looks like def update_lights(self, turn_on): if you can have the turn_on var in the original callback anyway.

this
```
def update_lights(self, turn_on):
```
doesnt bring anything more then
```
def update_lights(self, kwargs):
```
i pass arguments all the time and if its a callback i never thought that it was a problem.
i guess thats because most of my python learning was in the time i used AD, i am not predefined in python.

when it comes to make stuff more "pythonic" (allthough i really dislike that religion) i am not opposed to it, when it doesnt create big breaking changes, but most of all when it brings something.

but even with the worst case scenario it will save 1 line of code for an arg.
```
var_name = kwargs["var_name"]
```
and if its neccesary to call the callback as an ordinairy function you can always use
```
self.run_in(callback,0)
```

i think i am a bit more of a guy that adapts to the environment he is in instead of someone who wants to change the environment he is in to an environment he is used to elsewhere.

**Comment by TD22057** [comment]
I guess it's a difference of opinion then.  There is a reason that people like things to be as they expect.  There are standards and practices for all software communities.  When followed, they make the work easier and cause less wasted time, fewer bugs, and allow more things to work together more easily.

> def update_lights(self, turn_on):
> doesnt bring anything more then
> def update_lights(self, kwargs):

From my point of view, I have a hard time seeing why you think there isn't any difference between them..  The first one is clear and easy to understand what the arguments are.  The second one requires reading the code to figure out what to pass in, it takes more work to call, more work to maintain, and more work to document.  There is a reason that programming languages pass arguments as separate fields and not as a single argument.

I like to write libraries of functionality that I can reuse.  That means writing functions where the arguments are normal arguments.  I don't want to call my functions by making a dict of args.  Which of these is easier to understand and use?  I can glance at the first and tell what I should do.  The second requires that I read the whole function (or add a lot of documentation) to find out what arguments are going to be extracted.
```
def update_lights( turn_on, force_update=False ):
# vs
def update_lights( kwargs )
```

I understand that the current system doesn't work this way but changing it would be an improvement.  There is definitely a cost to doing this and it may or may not be worth paying.  I'd like to think if the choice is made to not do this, it will be because of the cost, not because there isn't any difference.

**Comment by ReneTode** [comment]
i guess the biggest difference is the way we use appdaemon.

appdaemon was created to make fast and small pieces of code, the python version from an automation in HA.
off course you can build complete systems around it, with inhereting classes etc. but that wasnt what AD wasnt originaly designed for.

off course Andrew has learned a lot over time and appdaemon evolved. and because he is a great guy he likes to give everyone the options that they like. which has made appdaemon more usefull for people who want to use it in other ways they the original purpose.

i embraced the original purpose and i still use it that way.
1 single (relative small) app and 150 times i call it with different yaml args.

and because i love to use it that way, i still have a hard time to see that people want to change things if the things are interfearing with the original purpose.

for me a general function that i have will always be called from a callback.
an app is an initialise that has some listeners and or schedulars.

so forgive me when i get a bit protective when there is talk about changes that dont fit the original purpose ;) for me thats like: he developer, i got a hard time getting a screw in the wall with this hammer, would you please adapt the hammer so it can be used as a screwdriver. because thats what i am more used to. 

but i know Andrew and he will find a way to make things more so that you guys are accomodated ;)

**Comment by efficiosoft** [comment]
@TD22057  +1 and thanks for explaining it so well.

@ReneTode There is more to this improvement than different views on how to use it. Things have been built and used for decades by millions of people for a reason. That might not be clear at first glance, but it's for sure more than just different syntax.

Using real keyword arguments does not only bring advantages for people using AD in a more advanced way, but only for beginnerss and 0-8-15-users (don't know whether that term exists internationally :D, but you'll know what I mean).

As a bonus, and to get this thread back to the original issue: It would obsolete the custom syntax validation and replace it with something better for free: it would validate if a callback accepts all keyword arguments that were passed by the user when he registered the callback with the scheduler and thus make **your** life (in terms of giving support) a lot easier.

**Comment by ReneTode** [comment]
> Things have been built and used for decades by millions of people for a reason
right, thats why there are so many things in python that you can do in so many different ways. because there is not just 1 view. thats why people still use python 2.7, thats why there are several type of logging
different syntax, is nothing more then different ways to do things, and there is no good or bad in that.

> It would obsolete the custom syntax validation and replace it with something better for free: it would validate if a callback accepts all keyword arguments that were passed by the user when he registered the callback with the scheduler and thus make your life (in terms of giving support) a lot easier.
my life wouldnt become any more easy from it. a single line that is always the same is way more easy to support, then something users can define themselves. i have no programs to check code when supporting, i just read the code.
and i am pretty sure that the biggest part from the AD users (at the moment) are users that use just a normal editor to create their code, and never use any kind of syntax validation. (like i dont either)

so i still stay with the point i made earlier: its the way AD is used that makes the difference of opinion.
appdaemonic is as much of a religion for me as pythonic is for "real" python guys ;)
be glad that Andrew is way less like that because most of my responses would be: "he, you are not programming right. the way you use it is not appdaemonic. try not so much to turn appdaemon into python ;) "  (and thats not far away from your response to users when they do stuff different then you intended with schedy and they complain about errors ;) )

**Comment by efficiosoft** [comment]
Let me quote the official PEP-20 - The Zen of Python:

> There should be one-- and preferably only one --obvious way to do it.
> Although that way may not be obvious at first unless you're Dutch.
> Now is better than never.

AD and the apps for it are written in Python, hence we should be grateful to the suggestions and wisdom provided by those who designed Python the way they did for a reason. Believe me, it'll make apps more performant, easier to write and read and also less error-prone.

The signature validation should not be done by you or any code editor. What I say is that AD would be able to generate a warning like "Hey, you forgot to accept the keyword argument xyz in your callback, it should be callback(xyz)" without you or Andrew having to implement anything custom yourselves. That's it what would make your life as a supporter easier... and resolve this issue btw.

Regarding Schedy, I'm sure you know that I'm always open for suggestions and - if well reasoned - implement them happily. When I reject something, that's then because of users not having understood how it can be done easier.

**Comment by ReneTode** [comment]
i think you quote these things to the wrong guy.

you are right, there is only one way to do it.
but your not dutch so its not obvious to you that it is the appdaemonic way ;)
but someday you will understand it, and see things the right way. maybe ill teach you some dutch before ;)

**Comment by efficiosoft** [comment]
The guy who wrote this is Dutch, as well as the one who started Python I think... But that line wasn't the one I was aiming at.

**Comment by efficiosoft** [comment]
Would be good if you also commented on the rest I wrote.

**Comment by acockburn** [comment]
OK, having considered all points of view I am going to:

1.  add **kwargs style callbacks - I like it better than what I ended up with and in all honesty I think it was my lack of familiarity in the very early days of python that led me to implement it that way. Now I know the difference between keyword unpacking and a dictionary I agree, **kwargs is more pythonic (sorry Rene!)

2. Make it backward compatible. Rene has long been my conscience, and I am not going to break who knows how many Apps just for some notion of pythonicness. One off config changes are one thing, but this change requires users to fine comb every app, make changes, re-test. That's a lot to ask for a hobbyist when they have a system that has been working well for a long time.

3. Default to the old style for a period of time - see above.

4. Make the new style the default eventually

**Comment by efficiosoft** [comment]
@acockburn Sounds good, thanks.

So just for my understanding: will you promote the new way in the docs and examples but still have the old way be the default? Because I don't think people will switch over themselves if they have to turn some non-default settings on proactively, and it'll become the same challenge for them when you pull the trigger and change the defaults at a later time.

I mean, it's a major version change (3.x to 4.x). Why not make the new style the default and, as @TD22057 suggested, allow for reverting it by something like

    self.use_old_kwargs = True

in ``initialize()``? That's an easy step to take for people not wanting to migrate yet, and you could use the new style in all examples and docs so that people get used to it.

**Comment by acockburn** [comment]
As I said above, I will default to the old style for a period of time, but will likely update the docs to push the new style, yes. But I will be doing the reverse of what you suggest. Initially it will be an opt-in:

```python
self.new_style_args=True
````

If you want to use it. Later on I will flip the default to True. This is in line with the way HASS introduces breaking changes and I think it is the kindest possible way to do so.

**Comment by efficiosoft** [comment]
Ok, just wanted to know because I imagine it's difficult to promote something in the docs which isn't done by default. But got it now, thanks.

**Comment by acockburn** [comment]
No worries - this has been a good discussion and I think we have arrived at a good place.

**Comment by efficiosoft** [comment]
Yes, think so as well.

Will you then also drop the custom signature validation and instead just call the callbacks and only give the hint on the signature when a ``TypeError`` is thrown? Would automagically resolve this issue and let Python do the heavy lifting for you.

**Comment by acockburn** [comment]
For new style callbacks, yes, that would be the intention - I like that the new style is more intuitive and solves this issue thoroughly :)

I'll probably keep it for old style callbacks.

**Comment by efficiosoft** [comment]
Ok... but where is the difference regarding signature validation between the two? I mean, I'll only use the new style, but why carry this code path along when the method would work equally well for both styles?

**Comment by TD22057** [comment]
@acockburn Thanks!  That looks great.

**Comment by efficiosoft** [comment]
Hi @acockburn 

Is there any progress on the callback signature validation? Do I now have the option to turn it off?

**Comment by acockburn** [comment]
Not yet - we are busy working on the beta but I want to get this in before we release the next official version

**Comment by efficiosoft** [comment]
Ah, great.

One more legal use case I noticed is blocked by this validation is this:

    def app_member(self):
        def handler(kwargs):
            pass
        self.run_every(handler, 30)

`handler` obviously has no `self` in this case and thus fails validation.

**Comment by efficiosoft** [comment]
Also keep in mind that signature inspection at every call is computationally expensive. Maybe move it to callback registration time and issue the warning there?

Or, even better:

```
try:
    execute_callback()
except TypeError as err:
    warn("Maybe the signature of your callback is wrong? It should be ...")
    warn("This exception was raised during calling the callback:")
    raise err from None
```

This way you only do the computation in case the invocation failed and don't even need to allow for disabling it.

**Comment by dlashua** [comment]
@acockburn if it helps any, this bit me too. I had lots of callbacks just using (self, *args, **kwargs) mostly because I could never remember the parameters and I wasn't going to use the data in my callback anyway.

**Comment by acockburn** [comment]
Starting to think about this again - I think at the very least I will add Robert's proposal for "just in time" signature checking - that should allow both patterns to work with the added bonus of logging the problem for less experienced users, and no breaking changes.

The change from kwargs as a dict to **kwargs may be more involved. I'll take a look, but might move that out to a point release after the beta is over as I want to get 4.0 out in a reasonable timeframe.

**Comment by acockburn** [comment]
@efficiosoft 
, @dlashua @TD22057 I just made a commit to the dev branch that optimizes the signature check along the lines that Robert suggested

1. Signature checking now only takes place if there is a TypeError exception when calling the callback
2. If the signature doesn't match as expected a warning is generated
3. If it does match it's likely a real TypeError in the callback so a stacktrace and error is generated as usual to the error log
4. If it's a real TypeError but the sig doesn;t match due to usages such as (*args, **kwargs) the signature check error will be output as there is no real way to check this, but you will also be able to see the stacktrace to see that it is a real TypeError in the code
5. The warning now says "Suspect incorrect signature type ..." and gives the expected type, because of the uncertainty in case 4

I'll leave this open to track the changes to kwargs that we discussed, but I think this fixes the most concerning nehavior highlighted in this bug.

**Comment by efficiosoft** [comment]
@acockburn Sounds great, thanks a lot for implementing! This removes one of the most demanding challenges of upgrading to 4.x I guess.

**Comment by beeblebrox** [comment]
> 5. The warning now says "Suspect incorrect signature type ..." and gives the expected type, because of the uncertainty in case 4
> 
> I'll leave this open to track the changes to kwargs that we discussed, but I think this fixes the most concerning nehavior highlighted in this bug.

I'm very happy that the sanitize will allow for *args, **kwargs in the pythonic way going forward.
Will you add an option to suppress the warnings on the callback/timer methods?  My biggest worry is that when I migrate some of my apps will cause very spammy logs.

**Comment by efficiosoft** [comment]
@beeblebrox There will be no warning unless your callback raises a `TypeError`, which happens e.g. when the function call failed due to an incompatible signature. When there is no exception, there won't be a warning either.

**Comment by Odianosen25** [comment]
I believe this has been fixed. Pls reopen if needed
