### ISSUE TITLE
Add SockJS Support to stream

### ISSUE THREAD

**Issue by acockburn** [AppDaemon/appdaemon#469]

**Comment by JZ-SmartThings** [comment]
THANK YOU!!!

**Comment by JZ-SmartThings** [comment]
@acockburn question: this one did not make it into v4.0.0, is that correct?

Thanks!

**Comment by acockburn** [comment]
Sadly not - I was planning to get it into 4.0.0 but my lack of time to work on it was holding up the release. In the end I decided to release anyway as I wanted to deliver python 3.8 compatibility and get people off the beta as well as get a Haas.io add on for 4.0. This feature is top of mind and I will get it in soon - certainly before I dig into anything else major.

**Comment by JZ-SmartThings** [comment]
Much appreciated, thank you @acockburn !

**Comment by JZ-SmartThings** [comment]
Hey @acockburn you may want to hold off because 4.x kinda broke all older iPads. iPad1, iPad2 and iPad3 all show the same gray icons that flicker that don't do anything when pressed. Even loading Hello dashboard just shows one large gray square. I'm using Safari but a few other browsers showed the same issue. Looks like 4.x changed something crucial to the functionality. I'm going to try the last 3.x release to make sure things come back. I'm also on the latest HA 0.103.6

**Comment by acockburn** [comment]
Thanks for the research - and I am seeing this too on 2 of my older iPads, still investigating. I have been running the beta happily right up to the last few days, and I am working on the theory that the upgrade to aiohttp has broken something since that went in right before the release. It's a little hard to troubleshoot on an iPad but I will be looking into it as my main downstairs panel is broken!

**Comment by acockburn** [comment]
Reverting the aiohttp version to the previous did not fix the issue so I'll need to do some more troubleshooting ...

**Comment by acockburn** [comment]
In fact I'll add a new issue for this

**Comment by acockburn** [comment]
Added #841 to track this.

**Comment by JZ-SmartThings** [comment]
Thank you sir! @acockburn sorry to be the bearer of bad news...

**Comment by acockburn** [comment]
Finally, SockJS support has now been added and is in the dev branch. Will be part of the 4.0.2 release.

**Comment by JZ-SmartThings** [comment]
Much apprecaited @acockburn! I did have to look at the change the "transport" option in the YAML file to "sockjs" in order to force it, though it did not help much in fixing the big issue with state updates.

I can't complain too much and you may simply choose to give up supporting older iPad 1 as it's super old. However, it's awesome to use the single button on it with the NoLockScreen hack which eliminates "Slide to unlock" screen. That makes it a decent wall panel device partially due to that Cydia hack.

I'm easily able to use iPad 2 and 3 Safari and experience zero problems. With iPad 1 though it does not seem to update an entity to its current state until the dashboard is refreshed. If using my older 3.0.5 build that was forked from you with socksjs support, I never had that problem. That was actually the biggest/only problem that socksjs is supposed to resolve --- that state update issue. Again, that's on an old iPad 1 while all newer devices work well. If you have an iPad 1 then it should be easily reproducible but I totally understand if you want to kill that level of backward compatibility.

**Comment by acockburn** [comment]
Thanks for the feedback - there are some issues with the code as it stands it seems as even on a modern iPad it disconnects after a short while so something is wrong., I’ll keep plugging away now you have confirmed that this worked ok on iPad 1 with the 3.x variant of the socksjs support.

**Comment by JZ-SmartThings** [comment]
Sorry for being "that guy" and truly appreciate the effort!

**Comment by Odianosen25** [comment]
I believe this has been fixed. Pls reopen if not. Regards
