### ISSUE TITLE
turn_on service not working with async apps

### ISSUE THREAD

**Issue by xaviml** [AppDaemon/appdaemon#848]
## What did I do
I bumped into an [issue](https://community.home-assistant.io/t/need-help-with-appdaemon-4-and-async/163937) from the community forum that resulted to be the same problem I had recently. Consider the following simple application:

```python
import appdaemon.plugins.hass.hassapi as hass

class Simple(hass.Hass):
    async def toggle(self, light):
        super().toggle(light)

    def initialize(self):
        self.create_task(self.toggle("light.0xccccccfffe995875_light"))
```

## What happened
Next error appears after 10 seconds that the app was initialized
```
2020-01-16 19:27:59.061352 WARNING test5: ------------------------------------------------------------
2020-01-16 19:27:59.062493 WARNING test5: Unexpected error running initialize() for test5
2020-01-16 19:27:59.063452 WARNING test5: ------------------------------------------------------------
2020-01-16 19:27:59.064921 WARNING test5: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 145, in initialize_app
    await utils.run_in_executor(self, init)
  File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 276, in run_in_executor
    response = future.result()
asyncio.exceptions.TimeoutError
2020-01-16 19:27:59.065899 WARNING test5: ------------------------------------------------------------
2020-01-16 19:27:59.072580 WARNING AppDaemon: Excessive time spent in utility loop: 10089.0ms, 10088.0ms in check_app_updates(), 1.0ms in other
```

However, if I remove the `async` keyword, it works. Also, if I change `super().toggle(light)` for `self.call_service("homeassistant/toggle", entity_id=light)` and leaving the `async`, it works.

So the problem is that `self.toggle` does not work with async features. It also does not work with `self.turn_on` and `self.turn_off`.

## What do I expect
I'd expect self.toggle to work with async functions.

**Comment by benleb** [comment]
Same here, tried to use this in my AutoMoLi app but it shows exactly the same behavior described here

**Comment by ReneTode** [comment]
all i can say is:

AD now has the option to create async apps, but that option is created to use where you cant get around it.
i wouldnt advise to start writing all apps in async, just because it can be done.

the threaded sync core from AD is way more stable, and apps build without async in general wont effect each other, which is good because you dont want all apps to fail, when 1 app fails.

that said ill ask @Odianosen25 or @dlashua to look at why those functions dont work with async, or what you need to get them to work.

**Comment by Odianosen25** [comment]
@xaviml,

It is true that the `turn_on` in async isn't working as I have tested it, and we will try fixing it before the next release.

**Comment by benleb** [comment]
argh shit, spent hours to debug this because I thought it must be my buggy code 😂🤦‍♀️

thanks in advance for fixing :D

**Comment by Odianosen25** [comment]
No worries 😂. But honestly still haven't figured out why it happens. Its a bit strange

**Comment by xaviml** [comment]
@benleb you can use self.call_service("homeassistant/turn_on") as a workaround.

**Comment by acockburn** [comment]
We will be looking at this for after the 4.0.1 begfix release

**Comment by Mithras** [comment]
I had the same issue and as a workaround just replaced turn_on() with call_service("<domain>.turn_on").

**Comment by oxan** [comment]
I think that the problem here is that the [`hass_check`](https://github.com/home-assistant/appdaemon/blob/dev/appdaemon/plugins/hass/hassapi.py) decorator calls `run_coroutine_threadsafe`, which submits a coroutine to the event loop and waits for its completion. However, since this method is called from the event loop itself, that waiting blocks the event loop and as such the coroutine we're waiting for never gets to run.

The cleanest solution is probably to invert the order of the `sync_wrapper` and `hass_check` decorators, and write the hass_check method in async style.

**Comment by oxan** [comment]
I've submitted #963 to fix this.

**Comment by mhoyer** [comment]
I also stepped into this issue. Any chance to see the already provided fix in an official build? Any further support needed?

**Comment by dekiesel** [comment]
> all i can say is:
> 
> AD now has the option to create async apps, but that option is created to use where you cant get around it.
> i wouldnt advise to start writing all apps in async, just because it can be done.
> 
> the threaded sync core from AD is way more stable, and apps build without async in general wont effect each other, which is good because you dont want all apps to fail, when 1 app fails.
> 
> that said ill ask @Odianosen25 or @dlashua to look at why those functions dont work with async, or what you need to get them to work.

Glad I read this, because I just considered switching to async apps because the documentation mentions that you can set the environment to async only, which I thought meant it's up to you what you want to use. Maybe the documentation could have a warning about this error?

**Comment by ReneTode** [comment]
its mentioned in the docs here:
https://appdaemon.readthedocs.io/en/latest/APPGUIDE.html#async-caveats

so yeah, you can use AD completely in async, but that also means that you shut down all protections that are build into AD, and you are responsible yourself to make sure that apps dont effect other apps and the AD core.

**Comment by dekiesel** [comment]
I meant that you don't advise to go full async, that the threaded approach is more stable and that async should be used where you can't get around it.

**Comment by ReneTode** [comment]
i would love to put that in the docs, but i am not a dev anymore ;) 

and the threaded approach is more stable, because of the fact that it has been there from the begining (that means that a lot of people use it for a long time, and the problems are all known or solved), and because apps dont have effect on each other or the core (what the docs warn about)

its exactly that why its my personal advise to use sync whenever you can.
the other devs leave it more up to the users.

**Comment by Mithras** [comment]
I went full async the moment it was introduced. I don't see any reason not to. Hopefully this will be default in future.
There are issues. Mostly because AppDeamon still tries to support both instead of getting rid of non-async completely.

**Comment by dekiesel** [comment]
Could you elaborate on the issues please, @Mithras ?

**Comment by Mithras** [comment]
@xaviml this will work but it's still not a good idea because this way AppDeamon will know nothing about the tasks you create and won't be able to handle them properly on restart, etc.
@dekiesel 
Async constrains don't work: https://github.com/AppDaemon/appdaemon/issues/922 (this one is easy to fix locally)
Whatever create_task() returns needs to be double awaited: https://github.com/AppDaemon/appdaemon/issues/921
That's about it. Everything else work fine for me. And my code is now 10 times simpler because I can utilize full power of async.

**Comment by ReneTode** [comment]
@Mithras i dont see why it should be default.
async is absolutely something that none experienced users shouldnt use.
and AD is absolutely not ready.
you just need to look at the latest issues and there is shown today that every async app effects other apps as it is now.
i dont know how much your house is automated, but i rather not have that when i have an unexpected error in an app about lights, that my heating stops working also.
i got over 600 selfwritten apps. and im no perfect person, so at some point there will always be an error.
if that causes all other apps to break down as well, that is a very very bad thing!!

AD will always support threaded apps in the future, because Andrew is never willing to break everything for 99% of the users.

and simple code is something that depends on the reader.
when i read your code i probably will find it way to complicated. ;)

**Comment by Mithras** [comment]
>i dont know how much your house is automated, but i rather not have that when i have an unexpected error in an app about lights, that my heating stops working also.
I've seen that statement a few times already. There is it coming from? My apps are not perfect and I do have errors. I have never seen an error in one app affecting other apps in any way though.

**Comment by Odianosen25** [comment]
@Mithras,

On Async constraints, please if you can respond to my query, that can be merged asap.

On AD being async by default, to be honest there see no way that is going to happen. I am also a heavy async user myself, but sync has its use cases outside the fact its simpler for new users. being able to utilize the inbuilt queuing mechanism for apps can be very vital.

I do understand your points, and will look at having it resolved as soon as we can.

Regards

**Comment by Mithras** [comment]
I think the main complication that comes with async is that any CPU heavy lifting should be extracted to a separate thread manually so that it doesn't block other apps. Which is pretty rare and I don't expect average user to ever need to worry about that.

**Comment by Odianosen25** [comment]
Well @Mithras on that, it should be handled well using the “run_in_executor” api unless I don’t understand what you mean. But if you meant to say long running sync methods, then you will be excited to know to solve such an issue, a new api “submit_to_executor” has just been added to dev. This will offload the heavy task to one of the executor threads and allow the app to continue other things.

Hopefully we will add a offloading to sub processes later on.

Regards

**Comment by ReneTode** [comment]
> I've seen this statement a few times already. Where is it coming from? My apps are not perfect either and I do have errors. I have never seen an error in one app affecting other apps in any way though.

thats probably because you know your way around async.
just yesterday in this issue:
https://github.com/AppDaemon/appdaemon/issues/834#issuecomment-758965787
it is clear that that user uses async, and there is a delay in the utility loop because there is a delay in the app.
a delay in the utility loop means that AD is on hold for that complete time.

if there is 1 thing that over 5 years of supporting AD has learned me, that users really dont know how to avoid threads hanging or being busy for to long.
in the latest versions (from AD 3 up) thats no problem, because all apps run in their own thread by default.
async apps dont run in a seperate thread. they run in the same thread as the AD core.
so ANY error that causes trouble for a thread (and there are quite a few you can make, that you didnt) will break the AD core.

if it ever comes to it i think the best way would be when the AD core is seperated from the apps (async in thread) and that async apps are also in seperate threads (with the option like it is now to run multiple apps in the same thread)

but that will need a complete rewrite from AD, so thats not going to happen soon.

untill that has happened, i as most active AD support (not dev) will keep my existing advise to only use async if you cant avoid it, unless you really know what you do (and even then i advise to make yourself familiar with the AD core before you start writing apps)

**Comment by Mithras** [comment]
@Odianosen25 yep, executors is what I meant by "extract to a separate thread manually". My point is that if you just run some code that takes 30 seconds to complete in the main loop (instead of using run_in_executor), no other callbacks will be called for these 30 seconds.

>a new api “submit_to_executor” has just been added to dev

Cool, thank you! I'll take a look what it does when I have time.

@ReneTode hmm, maybe I'm just lucky that I haven't experienced these issues. Anyway, it shouldn't be a fundamental async limitation. I'm pretty confident AppDaemon should be able to handle any errors in apps gracefully even when fully async.

**Comment by ReneTode** [comment]
> I'm pretty confident AppDaemon should be able to handle any errors in apps gracefully even when fully async.

thats probably something that needs some work.
but even that wont avoid other problems.
if an app comes into a loop (because there is something written unwell and somthing unforseen happens), in threaded (sync apps) that means that that app stops working.
but if you get the same problem in async, AD will hang completely and nothing works. because a loop in an app will mean that there is nothing going forward anymore, so also the AD core will stop.

i dont think anything should be a fundemental limitation.
but i only can repeat myself:
allthough nowadays you can use async in apps, AD isnt prepared to go fully async (yet)
at least not if you dont want to lose a lot of very good advantages that AD with sync apps offers.

**Comment by Mithras** [comment]
@ReneTode Well, async AppDaemon works the same way JavaScript works in the browser you are using right now and everybody seems to be fine with that. I mean yes, there are some limitations and browsers do sometimes hang because of that but IMO benefits way outweigh these limitations.

**Comment by ReneTode** [comment]
> Well, async AppDaemon works the same way JavaScript works in the browser you are using right now and everybody seems to be fine with that.

not everyone ;) 
for starting devs async writing is a horror. and allthough i use it, i dont like it.

> there are some limitations and browsers do sometimes hang because of that

thats exactly my point. you dont want your complete AD hanging. NEVER!
at least not when your complete house depends on AD running.

**Comment by Mithras** [comment]
@ReneTode Python is not my strongest language but would it be possible to run each async app in a separate thread? Like allow users to decide which app should be run in a separate thread instead of main thread or just a config option to create a separate thread for each async app. This way AppDaemon can be fully async while maintaining its reliability.

**Comment by ReneTode** [comment]
thats what i said before.

that would in my eyes be the ideal situation.
but to get that to happen the AD core needs to be completely rewritten.
and for that to happen Andrew needs to find the time and must be willing to do so.
and at least as the situation stands now it will be a long time before that will happen. (if ever)

and i think that such a heavy rewrite can only be done by Andrew. (unless a very very good dev is willing to spend a lot of time on it, and is able to convince Andrew to accept it)
