### ISSUE TITLE
Signature of callbacks on docs is incorrect

### ISSUE THREAD

**Issue by danielo515** [AppDaemon/appdaemon#939]
Hello, this section of the documentation:
https://github.com/home-assistant/appdaemon/blob/master/docs/APPGUIDE.rst#about-schedule-callbacks

Says that the callbacks should have the following signature:

```
def my_callback(self, kwargs):
```

But I think it should be:
```
def my_callback(self, **kwargs):
```

instead.
Is this a typo or is it intentionall? Sorry, python is not my main language and I'm not used to the conventions.

**Comment by ReneTode** [comment]
that is intentional.

you can also use

my_callback(self, anything_else):

**Comment by danielo515** [comment]
But will it be also a dictionary? So the two asterisks doesn't have any special effect?

**Comment by dlashua** [comment]
@danielo515 when you set up a scheduler event you can pass arbitrary keywords like so:

```self.run_in(self.cb, 60, a="b", c="d")```

When you do this, the kwargs parameter on the callback will contain those same arbitrary keywords.  This is designed to allow you to use the same callback function for different scheduler requests and use kwargs to differentiate between them. It can also be used to pass needed information into the callback that was known when the callback was scheduled.

If you don't use this feature, then kwargs will simply be equal to an empty dict.

You are correct that, generally, in python, by convention, we often see it used as "**kwargs". This is a companion to "*args" and allows for an unknown number of keyword arguments (or regular arguments, in the case of "*args"). This is not a use of that Python feature, we just happen to be using the same variable name in our examples (because they are, in fact, kwargs that were sent to the original callback request). You are welcome to use another variable name if it helps eliminate confusion. I.E:

```
  self.run_in(self.cb, 60, a="b", c="d")

def cb(self, original_keyword_arguments):
  self.log(original_keyword_arguments) # will print  a="b", c="d"
```

Hope that helps.
