### ISSUE TITLE
Appdemon listen_event callback filtering by "event" interfere with deconz 

### ISSUE THREAD

**Issue by SilverWx** [AppDaemon/appdaemon#987]
Here is a deconz event :
{
    "event_type": "deconz_event",
    "data": {
        "id": "salon_switch_1",
        "unique_id": "00:15:8d:00:03:6d:03:61",
        "event": 2002
    },
    "origin": "LOCAL",
    "time_fired": "2020-06-01T10:40:37.935253+00:00",
    "context": {
        "id": "ba8073b1b2004b25857658d9e4b59da3",
        "parent_id": null,
        "user_id": null
    }
}

event field of deconz event interfere with event parameter of listen_event callback as described is this thread : https://community.home-assistant.io/t/naming-error-with-deconz-and-appdaemon/40660/8

There is a way to bypass this problem by adding if statement for data["event"] in callback but it's not as fast and clean as filtering :)

**Comment by ReneTode** [comment]
there is always a possibility that var names from 1 program conflict with another.
and there is a workaround.
changing it would cause breaking changes for a lot of people.
and that probably the same answer that you will get when you ask HA is they are willing to change the var name on the HA side, or when you ask it anywhere else.

**Comment by SilverWx** [comment]
I understand that, and it's what I thought about before postinf this issue :/

Here is the easiest workaround I have found
https://community.home-assistant.io/t/naming-error-with-deconz-and-appdaemon/40660/27?u=silverwx

**Comment by ReneTode** [comment]
looking at it again, thats not even a workaround.
the event from deconz is inside a nested dict, and there is no way to filter inside nested dicts.
there is not even a conflict.

i got something simular:
you cant filter on entity_id with a call_service event., because entity ID is inside a dict.

so there is no interference, just not the possibility to filter inside dicts, which is obvious, because every data dict can be different.
